- readme.md
> feat: change readme

- lib/client/src/components/home-header.vue
> fix: 跳转首页404问题修复

- lib/client/src/views/system/index.vue
> fix: 外部跳转首页404问题

- lib/client/src/element-materials/modifier/component/slots/render-slot.vue
> fix: 配置数据回显不正确

- lib/client/src/views/project/index.vue
> feat: 应用内页导航支持展开收起

- lib/client/src/components/variable/variable-select/components/variable.vue
- lib/client/src/preview/index.js
- lib/server/controller/project-code.js
> 修复预览函数函数不生效 & 属性面板可以编辑项目变量

- lib/client/src/components/render/pc/components/draggable.vue
- lib/client/src/components/render/pc/resolve-component.vue
- lib/client/src/element-materials/core/Node.js
- lib/client/src/element-materials/core/extends/set-align.js
- lib/client/src/element-materials/core/extends/set-prop.js
- lib/client/src/element-materials/core/index.js
- lib/client/src/element-materials/core/static/utils.js
- lib/client/src/element-materials/modifier/component/align/index.vue
- lib/client/src/element-materials/modifier/component/form/index.vue
- lib/client/src/element-materials/modifier/component/gird/index.vue
- lib/client/src/element-materials/modifier/component/index.vue
- lib/client/src/element-materials/modifier/component/props/index.vue
- lib/client/src/element-materials/modifier/component/styles/index.vue
- lib/client/src/views/index/components/material-panel/components/common/group-box/hacker.js
- lib/client/src/views/index/index.vue
- lib/server/model/page-code.js
> fix: chart remote-options配置同步

- lib/server/controller/no-code.js
- lib/server/model/entities/flow.js
- lib/server/model/migrations/sqls/20220418081737-update-sql-up.sql
> nocode 对接 itsm服务相关接口

- lib/client/src/components/filelib/helper.ts
- lib/client/src/components/filelib/list-card.vue
- lib/client/src/components/filelib/list-table.vue
- lib/client/src/components/filelib/upload.vue
- lib/client/src/components/src-input/file-modal.vue
- lib/client/src/components/src-input/index.vue
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/element-materials/modifier/component/props/components/strategy/slot-wrapper.vue
- lib/client/src/element-materials/modifier/component/props/components/strategy/src.vue
- lib/client/src/views/project/file-manage/index.vue
- lib/client/src/views/project/index.vue
- lib/server/controller/file.js
> feat: 文件库支持上传常用文档和压缩包类型文件

- lib/server/controller/no-code.js
> nocode对接itsm接口

- lib/client/src/components/render/pc/index.vue
- lib/client/src/components/render/pc/tools/lesscode-margin/hooks/use-margin.js
- lib/client/src/components/render/pc/tools/lesscode-margin/index.vue
- lib/client/src/components/render/pc/tools/lesscode-resize/hooks/use-auto-width.js
- lib/client/src/components/render/pc/tools/lesscode-resize/hooks/use-resize.js
- lib/client/src/components/render/pc/tools/lesscode-resize/index.vue
- lib/client/src/element-materials/core/extends/clone-node.js
> feature: column,block布局中鼠标拖动组件位置

- lib/client/src/components/render/pc/index.vue
- lib/client/src/views/index/components/material-panel/components/panel-tree/index.vue
- lib/client/src/views/system/template-market.vue
> Feature margin

- lib/client/src/components/render/pc/index.vue
- lib/client/src/components/render/pc/widget/block.vue
- lib/client/src/components/render/pc/widget/column.vue
- lib/client/src/views/index/index.vue
> perf: 移除拖入组件时的默认间距

- lib/server/controller/no-code.js
> nocode 对接 itsm服务接口

- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
> fix: 兼容轮播图老的数组类型数据配置

- lib/client/src/components/filelib/file-icon.vue
- lib/client/src/components/filelib/list-card.vue
- lib/client/src/components/filelib/list-table.vue
- lib/client/src/views/project/file-manage/index.vue
> pref: 优化文件库文件预览图标的实现

- lib/client/src/element-materials/modifier/template/info.vue
> feat: 应用导航logo支持选择图片

- lib/client/src/components/src-input/index.vue
- lib/client/src/element-materials/modifier/template/index.vue
- lib/client/src/views/index/components/modifier-panel/index.vue
> pref: 优化布局导航配置面板样式

- lib/client/src/components/nocode-form/fields/table.vue
- lib/client/src/components/project/create-page-dialog.vue
- lib/client/src/components/render-nocode/data-manage/page-edit/buttonGroup.vue
- lib/client/src/components/render-nocode/data-manage/page-edit/index.vue
- lib/client/src/components/render-nocode/data-manage/page-use/filter-area.vue
- lib/client/src/components/render-nocode/data-manage/page-use/index.vue
- lib/client/src/components/render-nocode/data-manage/page-use/table-data.vue
- lib/client/src/components/render-nocode/form/components/form-content/index.vue
- lib/client/src/components/render-nocode/form/components/form-edit/fieldEdit.vue
- lib/client/src/components/render-nocode/form/index.vue
- lib/client/src/components/render-nocode/index.vue
- lib/client/src/components/ui/extra-links.vue
- lib/client/src/store/modules/nocode/form-setting.js
- lib/client/src/views/edit-nocode/components/action-tool/components/save.vue
- lib/client/src/views/project/flow-manage/edit/components/action-tool/components/save.vue
- lib/shared/no-code/constant.js
- lib/shared/no-code/validate.js
> Lesscode nocode

- lib/client/src/components/render/pc/index.vue
- lib/client/src/components/render/pc/resolve-component.vue
- lib/client/src/components/render/pc/tools/lesscode-margin/index.vue
- lib/client/src/components/render/pc/tools/lesscode-resize/index.vue
- lib/client/src/components/render/pc/tools/lesscode-tool/index.vue
- lib/client/src/element-materials/core/helper/commands/copy-paste.js
- lib/client/src/element-materials/core/menu.js
- lib/client/src/element-materials/core/static/reset.js
- lib/client/src/element-materials/core/widget/menu/create-menu.js
- lib/client/src/element-materials/core/widget/menu/index.vue
- lib/client/src/element-materials/modifier/component/form/index.vue
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/element-materials/modifier/component/slots/render-slot.vue
- lib/client/src/views/index/components/action-tool/components/clear-canvas.vue
> fix: 画布体验问题

- lib/client/src/preview/router.js
- lib/client/src/views/project/index.vue
- lib/server/project-template/project-init-code/lib/server/controller/user.js
> 预览展示导航和数据源相关优化

- lib/client/src/element-materials/core/index.js
> fix: 切换页面弹框提示问题

- lib/client/src/element-materials/modifier/component/form/index.vue
- lib/server/controller/variable.js
> 修复批量更新变量 & form 远程函数

- lib/client/src/components/render/mobile/simulator-area.vue
- lib/client/src/preview/index.js
- lib/client/src/preview/router.js
- lib/client/src/views/index/components/action-tool/components/preview.vue
- lib/client/src/views/preview/preview-mobile.vue
- lib/client/src/views/project/page.vue
- lib/shared/route/helper.js
> fix: 应用带版本预览优化

- lib/client/src/components/src-input/index.vue
- 修复在文件选择框中即时上传的文件使用后url非服务端地址的问题
> fix: 修复在文件选择框中即时上传的文件使用后url非服务端地址的问题

- lib/client/src/components/render/pc/tools/lesscode-tool/hooks/use-slot.js
> hotfix: 画布双击编辑文字

- lib/client/src/views/index/components/material-panel/components/common/group-box/index.vue
- lib/client/src/views/index/components/material-panel/components/common/group-box/render-custom-component.vue
- lib/client/src/views/index/components/material-panel/components/common/search-box/index.vue
- lib/client/src/views/index/components/material-panel/components/panel-component/components/render-custom-component.vue
> hotfix: 画布体验问题

- lib/client/src/components/render/pc/index.vue
> update: 交互式组件优化

- lib/client/src/components/render/pc/index.vue
> bugfix: 修复交互式组件提示文字的错位问题

- lib/server/controller/page.js
- lib/server/router/page.js
> bugfix: 修复复制页面加锁状态未去除的问题 & 修复加锁影响User信息的问题

- lib/client/src/components/render/pc/render-component.js
- lib/client/src/components/render/pc/render-slot.js
- lib/client/src/element-materials/core/Node.js
> hotfix: 组件 slot 更新

- lib/client/src/views/index/components/action-tool/components/common/use-save.js
> 修复chart组件remote必填

- lib/client/src/components/render/pc/widget/layout/components/left-right.vue
- lib/client/src/components/render/pc/widget/layout/components/top-bottom.vue
> bugfix: 修复导航组件区域选中问题

- lib/client/src/views/index/components/action-tool/components/common/use-save.js
> 修复flow组件remote必填

- lib/client/src/views/project/function-manage/api/children/list.vue
- lib/server/controller/api.js
- lib/server/controller/db-migration-helper.js
- lib/server/controller/function.js
- lib/server/model/entities/func-api.js
- lib/server/model/migrations/20220615124909-update-sql.js
- lib/server/model/migrations/sqls/20220518022855-update-sql-up.sql
- lib/server/model/migrations/sqls/20220615124909-update-sql-down.sql
- lib/server/model/migrations/sqls/20220615124909-update-sql-up.sql
- lib/server/service/data-service.js
- lib/server/service/function.js
- lib/shared/api/helper.js
> 函数与api关联关系

- lib/client/src/components/api/common/scheme-header.tsx
- lib/client/src/components/api/common/scheme.css
- lib/client/src/components/api/common/single-scheme.tsx
- lib/client/src/components/api/edit-scheme/response.vue
- lib/client/src/components/api/use-scheme/get.vue
- lib/client/src/components/api/use-scheme/post.vue
- lib/client/src/components/methods/forms/edit-func-form.vue
- lib/client/src/components/methods/forms/form-items/children/body-params.vue
- lib/client/src/components/methods/forms/form-items/children/query-params.vue
- lib/client/src/components/methods/forms/form-items/detail.vue
- lib/client/src/views/project/api-manage/children/create-api-sideslider/index.vue
- lib/client/src/views/project/api-manage/children/list.vue
- lib/client/src/views/project/data-source-manage/table-design/composables/table-info.ts
- lib/client/src/views/project/data-source-manage/table-design/edit-table.vue
- lib/client/src/views/project/data-source-manage/table-design/show-table.vue
- lib/client/src/views/project/data-source-manage/table-design/table-list/list/index.vue
- lib/client/src/views/project/index.vue
- lib/server/model/entities/data-table.js
- lib/server/model/migrations/20220621041055-update-sql.js
- lib/server/model/migrations/sqls/20220621041055-update-sql-down.sql
- lib/server/model/migrations/sqls/20220621041055-update-sql-up.sql
- lib/server/service/no-code.js
- lib/shared/api/helper.js
- lib/shared/no-code/helper.js
> api和数据源体验优化

- lib/server/controller/data-source.js
- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/controller/form.js
- lib/server/project-template/project-init-code/lib/server/service/data-service.js
- lib/server/project-template/project-init-code/lib/server/service/form.js
- lib/server/service/business/data-source.js
- lib/server/service/business/no-code.js
- lib/server/service/common/data-service.js
> 对接nocode全部接口

- lib/server/controller/data-source.js
- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/controller/form.js
- lib/server/service/business/data-source.js
> 对接nocode接口

- lib/server/project-template/project-init-code/lib/server/service/form.js
> 对接nocode生成源码

- lib/client/src/views/project/api-manage/children/create-api-sideslider/basic.vue
- lib/server/controller/data-source.js
- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/controller/form.js
> nocode 聚合接口

- lib/server/app.browser.js
> update: update prom buckets

- lib/server/app.browser.js
- update: update prom counter name
> update: update prom counter name

- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/controller/form.js
> nocode 接口支持 区间查询

- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/controller/form.js
- lib/server/project-template/project-init-code/lib/server/service/data-service.js
- lib/server/service/common/data-service.js
> nocode接口基于时间类型支持时区

- lib/client/src/views/project/data-source-manage/data-manage/render-function.vue
- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/controller/form.js
> nocode查询接口不携带formid

- lib/client/src/views/project/data-source-manage/data-manage/render-data.vue
- lib/server/service/business/preview-db-service.js
> 解决预览情况下时区错误问题

- lib/server/service/business/preview-db-service.js
> 添加预览环境db前缀

- lib/client/src/common/use-ajax-upload.js
- lib/client/src/components/filelib/list-card.vue
- lib/client/src/components/filelib/list-table.vue
- lib/client/src/components/filelib/upload.vue
- lib/client/src/components/filelib/use-upload-handler.js
- lib/client/src/views/project/release/publish.vue
- lib/client/src/views/project/version-manage/children/form-sideslider.vue
- 显示出文件上传失败原因
- 发布与版本日志输入框placeholder样式优化
> fix: 显示出文件上传失败原因和版本日志placeholder样式优化

- lib/client/src/components/variable/variable-form/index.vue
- lib/client/src/views/project/api-manage/children/create-api-sideslider/basic.vue
- lib/server/model/page-code.js
- lib/shared/function/helper.js
> 接口路径支持单引号，解决函数内引用报错问题

- lib/client/src/components/methods/forms/form-items/children/render-param-slot.css
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.tsx
- lib/client/src/components/methods/forms/form-items/detail.vue
- lib/server/service/business/function.js
> 修复函数参数引用变量关系

- lib/client/src/components/flow-form-comp/components/table-cell-value.vue
- lib/client/src/components/flow-form-comp/components/table-fields.vue
> Feat table display tag

- lib/client/src/components/api/common/scheme-tab.vue
- lib/client/src/components/api/common/scheme.css
- lib/client/src/components/api/common/single-scheme.tsx
- lib/client/src/components/dynamic-tag.vue
- lib/client/src/components/methods/edit-function-dialog/children/group.vue
- lib/client/src/components/methods/edit-function-dialog/children/item.vue
- lib/client/src/components/methods/edit-function-dialog/index.vue
- lib/client/src/components/methods/forms/edit-func-form.vue
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.css
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.tsx
- lib/client/src/components/methods/forms/form-items/detail.vue
- lib/client/src/components/methods/forms/form-items/token.vue
- lib/client/src/components/variable/variable-form/index.vue
- lib/client/src/components/variable/variable-select/components/variable.vue
- lib/server/service/business/function.js
> 函数和api体验问题修复

- lib/server/conf/http.js.example
- lib/server/controller/no-code.js
- lib/server/controller/release.js
- lib/server/project-template/project-init-code/lib/server/app.browser.js
> 对接 nocode apigateway

- lib/client/src/preview/router.js
- lib/server/model/project-code.js
- lib/shared/route/helper.js
> fix: 修复应用预览在跳转路由时导航菜单未高亮问题

- lib/server/project-template/project-init-code/package.json
- package.json
> update apigateway-sdk version

- lib/server/controller/no-code.js
> itsm apigateway 添加 bktoken

- lib/server/app.browser.js
- lib/server/controller/perms-migration-helper.js
- lib/server/model/entities/perms-migration.js
- lib/server/model/migrations/20220707034530-update-sql.js
- lib/server/model/migrations/sqls/20220707034530-update-sql-down.sql
- lib/server/model/migrations/sqls/20220707034530-update-sql-up.sql
- lib/server/model/project.js
- lib/server/model/sql/20220707/update.sql
- lib/server/router/project.js
> feat: add access iam

- lib/server/controller/page.js
- lib/server/controller/project.js
- lib/server/model/project.js
> feat: update access iam

- lib/server/app.browser.js
- lib/server/controller/iam-migration-helper.js
- lib/server/controller/iam.js
- lib/server/controller/project.js
- lib/server/model/entities/iam-migration.js
- lib/server/model/migrations/sqls/20220707034530-update-sql-up.sql
- lib/server/model/sql/20220707/update.sql
- lib/server/router/iam.js
- lib/server/router/project.js
> update: 名称调整  perm => iam

- lib/client/src/views/project/release/components/deploy-log/index.vue
- lib/client/src/views/project/release/components/deploy-log/render-stage.vue
- lib/client/src/views/project/release/components/running-log.vue
- lib/client/src/views/project/release/publish.vue
> feat: 修改部署日志交互

- lib/client/src/components/api/choose-api.vue
- lib/server/service/business/open-api.js
> api 添加新增入口

- lib/server/model/project.js
> fix: 复制应用基于应用的默认版本

- lib/server/project-template/project-init-code/lib/server/conf/open-api.json
- lib/server/project-template/project-init-code/lib/server/service/form.js
- lib/server/service/business/open-api.js
- lib/server/system-conf/open-api.json
> 生成的网关支持子路径访问

- lib/server/controller/iam.js
> update: add 调试日志

- lib/server/controller/iam.js
- lib/server/service/common/data-service.js
> update: 权限中心资源拉取 列表搜索

- lib/server/controller/iam.js
- update: 权限中心资源拉取 列表搜索 id 和 projectCode 两个字段 or 模糊查询
> update: 权限中心资源拉取 列表搜索 id 和 projectCode 两个字段 or 模糊查询

- lib/server/controller/iam.js
> fix: 修复获取 keyword 关键字的错误

- .gitignore
- lib/server/conf/iam.js.example
- lib/server/controller/iam-migration-helper.js
> update: 对接权限中心配置文件位置调整

- lib/client/src/element-materials/core/static/parse-data.js
- lib/client/src/element-materials/materials/vant/h5-container/index.js
- lib/server/model/page-code.js
> fix: 修复rpx单位问题；新建page的content为空布局

- lib/server/controller/iam-migration-helper.js
> add: 注册全部操作

- lib/server/controller/iam-migration-helper.js
> feat: add 操作组

- lib/server/middleware/auth.js
- lib/server/model/project-code.js
- lib/server/project-template/project-init-code/lib/server/app.browser.js
> 有流程的情况下生成apigateway

- lib/client/src/views/project/page-manage/children/list-card.vue
- lib/client/src/views/system/project-manage/children/list-card.vue
- lib/client/src/views/system/project-manage/children/list-table.vue
- lib/client/src/views/system/project-manage/index.vue
> fix: 应用管理页添加部署入口及卡片布局在小屏下的宽度优化

- lib/client/src/components/api/choose-api.vue
> 修改api和apigateway交互

- lib/client/src/components/methods/forms/form-items/monaco.vue
- lib/client/src/element-materials/core/helper/find-related-method.js
- lib/client/src/element-materials/materials/bk/select/index.js
- lib/client/src/element-materials/materials/bk/transfer/index.js
- lib/client/src/element-materials/modifier/component/directives/index.vue
- lib/client/src/element-materials/modifier/component/events/children/render-event.vue
- lib/client/src/element-materials/modifier/component/events/index.vue
- lib/client/src/element-materials/modifier/component/slots/components/common/select-key.vue
- lib/client/src/element-materials/modifier/component/slots/components/select-data-source.vue
- lib/client/src/element-materials/modifier/component/slots/components/select-remote.vue
- lib/client/src/element-materials/modifier/component/slots/render-config/bk/index.js
- lib/client/src/element-materials/modifier/component/slots/render-slot.vue
- lib/server/controller/db-migration-helper.js
- lib/server/model/page-code.js
> 数据源、select、事件使用体验问题

- lib/client/src/components/choose-data-table.vue
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.css
- lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
- lib/client/src/element-materials/modifier/component/slots/components/common/select-key.vue
- lib/client/src/element-materials/modifier/component/slots/components/select-data-source.vue
- lib/client/src/element-materials/modifier/component/slots/components/select-remote.vue
> select和函数体验问题

- lib/client/src/components/methods/forms/form-items/token.vue
- lib/server/controller/mock-data.js
> 优化 token 提示

- lib/server/service/business/no-code.js
> 表单默认携带 operate_at、operator 字段

- lib/server/model/project-code.js
- lib/server/project-template/project-init-code/lib/server/conf/apigw.js
- lib/server/project-template/project-init-code/lib/server/controller/form.js
> 生成源码对接itsm

- lib/server/controller/iam.js
- feat: 权限中心拉取 lesscode 项目，去掉 isOffcial 条件
> feat: 权限中心拉取 lesscode 项目，去掉 isOffcial 条件

- lib/client/src/api/index.js
- lib/client/src/api/pureAxios.js
- lib/client/src/components/api/choose-api.vue
- lib/client/src/components/choose-data-table.vue
- lib/client/src/components/methods/edit-function-dialog/index.vue
- lib/client/src/components/methods/forms/form-items/monaco.vue
- lib/client/src/components/patch/widget-bk-table/index.vue
- lib/client/src/components/patch/widget-table-column/index.vue
- lib/client/src/components/render/pc/render-component.js
- lib/client/src/element-materials/modifier/component/props/components/strategy/pagination.vue
- lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
- lib/client/src/views/project/api-manage/children/list.vue
- lib/server/controller/data-source.js
- lib/server/controller/db-migration-helper.js
- lib/server/model/page-code.js
- lib/server/project-template/project-init-code/lib/client/src/api/index.js
- lib/server/project-template/project-init-code/lib/client/src/api/pureAxios.js
- lib/server/project-template/project-init-code/lib/server/controller/data-source.js
- lib/server/project-template/project-init-code/lib/server/service/data-source.js
- lib/server/service/business/data-source.js
- lib/shared/data-source/helper.js
> 0729发布问题修复

- lib/server/controller/mock-data.js
- lib/server/project-template/project-init-code/lib/server/controller/mock-data.js
- lib/server/project-template/project-init-code/lib/server/service/data-source.js
- lib/server/service/business/data-source.js
> select时间处理

- lib/server/controller/mock-data.js
- lib/server/project-template/project-init-code/lib/server/controller/mock-data.js
> select 时间优化

- lib/client/src/views/preview/preview-template.vue
- lib/server/controller/vue-code.js
- lib/server/model/page-code.js
> fix: 修复h5模板预览问题 #355

- lib/client/src/views/preview/preview-template.vue
> fix: 修复css样式书写错误 #355

- lib/client/src/components/patch/widget-bk-table/index.vue
- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/service/data-service.js
- lib/server/project-template/project-init-code/lib/server/service/data-source.js
- lib/server/service/business/data-source.js
- lib/server/service/business/no-code.js
- lib/server/service/common/data-service.js
> 空字符串入库时间字段置为null，调试更新nocode表

- lib/server/controller/no-code.js
- lib/server/project-template/project-init-code/lib/server/service/data-service.js
- lib/server/service/business/no-code.js
- lib/server/service/common/data-service.js
> 数据入库兼容 date 空字符串

- lib/server/project-template/project-init-code/lib/server/service/data-service.js
- lib/server/project-template/project-init-code/lib/shared/constant.js
- lib/server/project-template/project-init-code/lib/shared/util.js
- lib/server/service/common/data-service.js
> 数据入库前校验json字段格式

- lib/server/model/page-code.js
> 模板预览table属性失效问题

- lib/client/src/components/patch/widget-table-column/index.vue
- lib/server/project-template/project-init-code/lib/server/service/data-service.js
- lib/server/service/common/data-service.js
> json字段支持json string 格式数据

- package.json
- feat: add build --max_old_space_size=4096
> feat: add build --max_old_space_size=4096

- lib/client/src/views/system/project-manage/children/list-card.vue
- lib/client/src/views/system/project-manage/children/list-table.vue
- package.json
- feat: max_old_space_size 改为 2048；暂无应用，立即创建添加 create_app 鉴权
> feat: max_old_space_size 改为 2048；暂无应用，立即创建添加 create_app 鉴权

- lib/server/controller/iam.js
- feat: add createApplyUrl params log
> feat: add createApplyUrl params log

- lib/server/controller/iam-migration-helper.js
- feat: update System provider_config.host
> feat: update System provider_config.host

- lib/server/controller/project.js
- lib/server/middleware/auth.js
> update: add log

- lib/server/controller/project.js
- lib/server/middleware/auth.js
> update: remove log

- lib/server/middleware/auth.js
- fix: 新用户创建项目从 username 获取用户名而不是 bk_username
> fix: 新用户创建项目从 username 获取用户名而不是 bk_username

- lib/server/middleware/auth.js
- fix: 社区版 bk_username，内部版 username
> fix: 社区版 bk_username，内部版 username

- lib/client/src/views/edit-nocode/index.vue
- lib/client/src/views/index/index.vue
- lib/client/src/views/project/index.vue
- lib/client/src/views/project/release/publish.vue
- lib/server/controller/api.js
- lib/server/controller/data-source.js
- lib/server/controller/iam.js
- lib/server/controller/no-code.js
- lib/server/controller/project-code.js
- lib/server/controller/project.js
- lib/server/decorator/authorization/index.js
- lib/server/router/component-category.js
- lib/server/router/component.js
- lib/server/router/open-api.js
- lib/server/router/page.js
- lib/server/router/project-version.js
- lib/server/router/project.js
- lib/server/router/release.js
1. 后端校验中，如果是应用创建者本身，那么默认具有应用相关的权限，这里减少了对权限中心的请求
2. 权限中心验证方法氛围 check（前端接口调用）和 checkInServer（后端直接调用）
3. 接口 router 更细力度的划分权限
4. 项目内页面列表页左侧菜单鉴权
> 对接权限中心功能优化：

- lib/client/src/App.vue
> feat: navbar 调整

- lib/client/src/App.vue
- lib/client/src/views/home/index.vue
- lib/client/src/views/system/index.vue
> feat: 画布navbar

- lib/client/src/components/render/mobile/index.vue
- lib/client/src/components/render/pc/tools/lesscode-resize/hooks/use-full-width.js
- lib/client/src/components/render/pc/tools/lesscode-tool/index.vue
- lib/shared/util.js
> fix: 修复H5容器体验错误与移动端bug

- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/render-group.vue
> group监听查询历史

- lib/server/middleware/auth.js
> 添加应用对apigateway的jwt鉴权

- package.json
- feat: update terser-webpack-plugin version
> feat: update terser-webpack-plugin version

- package.json
- feat: --max_old_space_size => --max-old-space-size
> feat: --max_old_space_size => --max-old-space-size

- lib/client/src/api/index.js
- lib/client/src/components/apply-permission/apply-dialog.vue
- lib/client/src/components/auth/button.vue
- lib/client/src/components/auth/component.js
- lib/client/src/store/modules/iam.js
- lib/client/src/views/project/index.vue
- lib/client/src/views/system/project-manage/children/list-card.vue
- lib/client/src/views/system/project-manage/children/list-table.vue
- lib/server/controller/iam.js
- lib/server/controller/project.js
- lib/server/router/component-category.js
- lib/server/router/component.js
- lib/server/router/open-api.js
- lib/server/router/page.js
- lib/server/router/project-code.js
- lib/server/router/project-version.js
- lib/server/router/project.js
- lib/server/router/release.js
对接权限中心体验优化：
1. 区分接口鉴权以及页面鉴权：server router 返回新增 permissionType 属性，值为 page
2. 页面列表页左侧菜单鉴权优化，通过当前项目的操作权限来鉴权，避免发送多个请求
3. project/detail, iam/my-project 两个接口中返回的项目信息加上 canDevelop, canDeploy, canManagePerms, canManage 四个属性
> 对接权限中心体验优化

- lib/client/src/components/monaco.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-enable.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/render-table.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/index.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/query-history.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/query-result.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/sql-query.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
- lib/server/controller/data-source.js
- lib/server/project-template/project-init-code/lib/server/controller/data-source.js
- lib/server/project-template/project-init-code/lib/server/service/data-source.js
- lib/server/service/business/data-source.js
> 数据操作体验问题修复

- lib/server/controller/iam.js
- feat: 新建应用 创建应用分级管理员时 分级管理员可授权的人员范围修改为全体人员
> feat: 新建应用 创建应用分级管理员时 分级管理员可授权的人员范围修改为全体人员

- lib/client/src/components/render/pc/tools/lesscode-tool/index.vue
- lib/client/src/views/system/project-manage/children/list-card.vue
- lib/client/src/views/system/project-manage/children/list-table.vue
- lib/server/controller/iam.js
- lib/server/controller/project.js
- [feat: 去掉 createUser 的逻辑，权限控制全由权限中心来管理](https://github.com/TencentBlueKing/bk-lesscode/commit/e5e33cc15890ade24aef20d6ca172ff960821fe8)
> feat: 去掉 createUser 的逻辑，权限控制全由权限中心来管理

- package.json
- --max-old-space-size 2048 => 1024
> --max-old-space-size 2048 => 1024

- package.json
- --max-old-space-size 1024 => 3072
> --max-old-space-size 1024 => 3072

- package.json
- --max-old-space-size 3072 => 2048
> --max-old-space-size 3072 => 2048

- lib/client/src/api/index.js
- lib/client/src/views/project/index.vue
- lib/server/controller/iam.js
- lib/server/router/iam.js
> feat: 修复体验问题

- lib/client/src/store/index.js
- lib/client/src/views/system/template-market.vue
- lib/server/controller/iam.js
- lib/server/controller/project.js
- lib/server/router/project-code.js
- feat: 应用模板、页面模板相关权限处理（不需要鉴权）
> feat: 应用模板、页面模板相关权限处理（不需要鉴权）

- lib/client/src/components/methods/forms/form-items/monaco.vue
- lib/client/src/components/variable/variable-form/index.vue
- lib/client/src/components/variable/variable-form/variable-code.vue
> 添加计算变量使用提示

- lib/server/controller/iam-migration-helper.js
> feat: 平台老的权限逻辑迁移，移除测试数据

- lib/client/src/components/dynamic-tag.vue
> 修复：函数切换编辑的时候，参数区域未变成添加icon

- package.json
> 复合组件（表格类），支持更新表头

- lib/server/controller/iam-migration-helper.js
> feat: 迁移权限出错后继续执行

- lib/server/controller/data-source.js
- lib/server/controller/function-market.js
- feat: 数据源管理以及函数库 ProjectAuthorization 装饰器加上 needAuthActions 参数
> feat: 数据源管理以及函数库 ProjectAuthorization 装饰器加上 needAuthActions 参数

- lib/client/src/views/system/project-manage/children/list-card.vue
> feat: 去掉项目列表页的调试信息

- lib/client/src/components/field-table/field-table.tsx
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/index.vue
> 数据源默认字段不可删除

- lib/client/src/store/modules/project.js
- lib/client/src/views/project/component-manage/public-scope.vue
- lib/client/src/views/project/index.vue
- lib/server/app.browser.js
- lib/server/controller/iam-migration-helper.js
- lib/server/controller/iam.js
- lib/server/controller/project.js
- lib/server/decorator/authorization/index.js
> feat: 本地开发时去掉权限中心鉴权相关的逻辑

- lib/client/src/components/api/choose-api.vue
> 没有项目的情况下，不可选择自建api和数据表

- lib/server/controller/data-source.js
- lib/server/model/entities/base.js
- lib/server/model/project.js
> 修复复制项目表结构缺失问题

- lib/server/model/project.js
> 复制项目的时候，携带tableid

- lib/server/model/page-code.js
> feat: 导航主题色新版方案实现

- lib/client/src/components/api/common/scheme.css
- lib/client/src/components/api/common/single-scheme.tsx
- lib/client/src/components/api/create-api-sideslider/basic.vue
- lib/client/src/components/api/create-api-sideslider/index.vue
- lib/client/src/components/api/edit-scheme/response.vue
- lib/client/src/components/methods/edit-function-dialog/index.vue
- lib/client/src/components/methods/forms/show-func-dialog.vue
- lib/client/src/views/project/api-manage/children/category.vue
- lib/client/src/views/project/api-manage/children/list.vue
- lib/client/src/views/project/function-manage/children/group.vue
- lib/client/src/views/system/function-market.vue
> 函数和api体验问题优化

- lib/client/src/views/project/api-manage/children/list.vue
- lib/client/src/views/project/data-source-manage/data-table/data-manage/render-data.vue
- lib/client/src/views/project/data-source-manage/data-table/table-design/table-list/list/index.vue
- lib/client/src/views/system/function-market.vue
> 函数&api体验问题

- lib/client/src/views/system/project-manage/index.vue
- lib/server/controller/open-api.js
- lib/server/controller/project.js
- lib/server/middleware/auth.js
- fix: 修复本地开发时，创建应用对接权限中心的问题；以及创建 demo 项目时，需要加上对接权限中心的逻辑
> fix: 修复本地开发时，创建应用对接权限中心的问题；以及创建 demo 项目时，需要加上对接权限中心的逻辑

- lib/client/src/views/project/data-source-manage/data-operation/index.vue
- lib/server/controller/db-migration-helper.js
- lib/server/project-template/project-init-code/lib/server/service/bk-base.js
- lib/server/service/business/bk-base.js
> 对接 bk-base

- lib/client/src/element-materials/core/extends/clone-node.js
- lib/client/src/element-materials/core/static/parse-template.js
> 修复模板和复制使用 v-for 异常

- lib/client/src/components/patch/widget-bk-table/index.vue
- lib/client/src/components/render/pc/render-component.js
- lib/client/src/element-materials/modifier/component/props/components/strategy/table-data-source.vue
- lib/server/controller/db-migration-helper.js
- lib/server/model/page-code.js
> table 支持设置是否展示操作列

- lib/server/model/page-code.js
> table支持设置是否展示操作列

- lib/client/src/components/choose-data-table.vue
- lib/client/src/element-materials/modifier/component/slots/components/common/select-key.vue
- lib/client/src/element-materials/modifier/component/slots/components/select-data-source.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
> 对接 bkbase 体验问题

- lib/client/src/components/variable/variable-table.vue
> 删除变量弹层文案样式优化

- lib/client/src/element-materials/materials/bk/column/index.js
- lib/client/src/element-materials/materials/bk/paragraph/index.js
- lib/client/src/element-materials/materials/vant/paragraph/index.js
- lib/client/src/element-materials/modifier/component/directives/index.vue
- lib/client/src/element-materials/modifier/component/styles/common/util.js
- lib/client/src/element-materials/modifier/component/styles/layout/item.vue
- lib/client/src/element-materials/modifier/component/styles/strategy/font.vue
- lib/client/src/element-materials/modifier/component/styles/strategy/position.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
> 组件属性配置文案统一

- lib/server/service/business/bk-base.js
> 修改调用 bk-base 接口

- lib/client/src/element-materials/materials/bk/block/index.js
- lib/client/src/element-materials/materials/bk/column/index.js
- lib/client/src/element-materials/materials/bk/free-layout/index.js
- lib/client/src/element-materials/materials/bk/grid/index.js
- lib/client/src/element-materials/modifier/component/directives/index.vue
- lib/server/model/page-code.js
布局类组件增加 v-bkloading 指令，其余组件增加 v-bk-tooltips 指令
> 布局类组件增加 v-bkloading 指令，其余组件增加 v-bk-tooltips 指令

- lib/client/src/components/choose-data-table.vue
- lib/client/src/components/minus-icon.vue
- lib/client/src/components/plus-icon.vue
- lib/client/src/store/modules/data-source.js
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-bk-base-table.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-condition.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-type.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/render-table.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/index.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/query-result.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
- lib/server/controller/data-source.js
- lib/server/service/business/bk-base.js
- lib/shared/data-source/helper.js
> 优化对接bk-base交互

- lib/client/src/components/choose-data-table.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-join.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
- lib/server/project-template/project-init-code/lib/server/controller/data-source.js
> 优化对接 bk-base 体验

- lib/client/src/components/methods/choose-function/index.vue
- lib/client/src/components/variable/variable-select/index.vue
- lib/client/src/components/variable/variable-table.vue
- lib/client/src/element-materials/core/Node.js
- lib/client/src/element-materials/core/helper/find-related-method.js
- lib/client/src/element-materials/core/helper/find-related-variable.js
- lib/client/src/element-materials/modifier/component/events/children/render-event.vue
- lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
- lib/client/src/views/index/components/action-tool/components/common/use-save.js
- lib/client/src/views/index/components/operation-area/components/page-function.vue
- lib/server/controller/db-migration-helper.js
- lib/server/controller/page.js
- lib/server/model/page-code.js
> 函数执行参数支持变量

- lib/client/src/components/choose-data-table.vue
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
- lib/server/project-template/project-init-code/lib/server/service/bk-base.js
- lib/server/service/business/bk-base.js
> 对接 bk-base 体验问题修复

- lib/client/src/components/render/mobile/widget/component-action-use.js
- lib/client/src/element-materials/materials/vant/h5-page/index.js
- lib/server/model/page-code.js
> bugfix: 修改h5背景图大小默认为100% && 修复PC路由无法高亮的问题

- lib/client/preview.html
- lib/client/src/components/render/mobile/area.scss
- lib/client/src/components/render/mobile/common/mobile-header.vue
- lib/client/src/components/render/mobile/simulator-area.vue
- lib/client/src/element-materials/materials/vant/cell/index.js
- lib/client/src/element-materials/materials/vant/icon/index.js
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/element-materials/modifier/component/props/components/strategy/route-list.vue
- lib/client/src/views/preview/preview-mobile.vue
- lib/client/src/views/preview/preview-template.vue
> fix(mobile): 移动端组件属性优化

- lib/client/src/views/index/index.vue
- package.json
> 修复页面切换预览失效问题

- lib/client/src/components/choose-data-table.vue
- lib/client/src/components/variable/variable-select/index.vue
- lib/client/src/element-materials/modifier/component/directives/index.vue
- lib/client/src/views/project/data-source-manage/data-table/data-manage/render-data.vue
- lib/server/model/page-code.js
> v-for 指令支持数据表

- lib/client/src/components/filelib/helper.ts
- lib/client/src/components/filelib/use-upload-handler.js
- lib/server/controller/file.js
- lib/server/system-conf/operate-log.js
- 文件上传接口添加异常捕获避免创建错误数据
- 页面更新的操作审计兼容不存在页面名称的调用
> fix: 添加文件上传异常捕获及操作审计兼容不存在页面名称的调用

- lib/client/src/element-materials/modifier/component/directives/index.vue
- lib/client/src/views/index/components/page-list/index.vue
- lib/client/src/views/index/index.vue
> 修复 pc 预览失效 & 修改 v-for 提示

- lib/client/src/views/preview/preview-template.vue
> fix(mobile): 修复移动端模板预览没有手机的问题

- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-table-field.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-table.vue
- lib/shared/data-source/helper.js
- lib/shared/data-source/sql-builder.js
> 修改bk-base 生成的sql

- lib/client/src/views/system/operation/stats/comp/dim-comp.vue
- lib/client/src/views/system/operation/stats/export-button.vue
- lib/client/src/views/system/operation/stats/func/dim-func.vue
- lib/client/src/views/system/operation/stats/project/dim-project.vue
- lib/client/src/views/system/operation/stats/user/dim-user.vue
- lib/server/controller/operation.js
> feat: 运营数据只统计默认版本及导出调整为查询到的所有数据

- lib/server/controller/operation.js
> feat: 运营数据接口单页上限调整为500条

- lib/client/src/views/preview/preview-template.vue
- lib/server/model/page-code.js
> fix(h5-template): 修复H5模板预览出错的问题

- lib/server/controller/db-migration-helper.js
> 减少刷数据时内存消耗

- lib/server/service/business/bk-base.js
> 过滤无效 bk-base 数据

- lib/client/src/components/render/mobile/area.scss
- lib/client/src/components/render/mobile/common/mobile-header-height.js
- lib/client/src/components/render/mobile/common/mobile-header.vue
- lib/client/src/components/render/mobile/common/simulator-mobile.scss
- lib/client/src/components/render/mobile/common/simulator-mobile.vue
- lib/client/src/components/render/mobile/simulator-area.vue
- lib/client/src/components/render/pc/components/draggable.vue
- lib/client/src/element-materials/core/static/reset.js
- lib/client/src/element-materials/materials/vant/h5-container/index.js
- lib/client/src/views/preview/preview-mobile.vue
- lib/server/model/page-code.js
H5组件优化:
- 支持获取H5实例,进行JS编程
- 添加H5翻页器是否显示的选项
- 当拖入非Root容器,进行使用提示
- xxxx
- Fixes #
> feat(H5): 优化H5代码结构 & 添加H5实例 & 添加H5分页器是否显示属性

- lib/client/src/views/project/app-perm-model/app-perm-model-sideslider.vue
- lib/client/src/views/project/app-perm-model/index.vue
- lib/server/controller/db-migration-helper.js
- lib/server/controller/iam.js
- lib/server/model/page.js
- lib/shared/constant.js
> feat: 修改操作对接后端接口

- lib/server/controller/db-migration-helper.js
- lib/server/controller/iam-migration-helper.js
- lib/server/controller/iam.js
- lib/server/model/iam-app-perm.js
- lib/server/router/iam.js
- feat: 应用权限模型，注册系统、注册资源类型、注册实例视图、注册操作、添加权限中心回调接口
> feat: 应用权限模型，注册系统、注册资源类型、注册实例视图、注册操作、添加权限中心回调接口

- lib/server/controller/db-migration-helper.js
- lib/server/controller/iam.js
> feat: 权限中心回调接口 参数变更

- lib/server/controller/iam.js
> feat: 权限中心回调 list_instance

- lib/client/src/views/project/app-perm-model/app-perm-model-sideslider.vue
- lib/client/src/views/project/app-perm-model/index.vue
- lib/server/controller/db-migration-helper.js
- lib/server/controller/iam.js
- lib/shared/constant.js
- feat: list_instance 回调接口，拉取资源时根据 lesscode 系统关联资源来决定
> feat: list_instance 回调接口，拉取资源时根据 lesscode 系统关联资源来决定

- lib/server/controller/iam.js
> feat: search_instance 回调接口

- lib/server/model/project-code.js
- feat: 生成项目里，router meta 中加上 pageId，拖拽应用内对页面进行鉴权
> feat: 生成项目里，router meta 中加上 pageId，拖拽应用内对页面进行鉴权

- lib/client/src/main.js
- lib/server/controller/iam.js
- lib/server/model/project-code.js
- feat: 生成项目中，路由里 meta 信息加入内置操作资源 page 的信息
> feat: 生成项目中，路由里 meta 信息加入内置操作资源 page 的信息

- lib/client/src/views/project/app-perm-model/index.vue
- lib/server/controller/project.js
- lib/server/model/iam-app-perm.js
- feat: 新建项目时初始化 iam-app-perm 数据 && 先去掉新建操作按钮
> feat: 新建项目时初始化 iam-app-perm 数据 && 先去掉新建操作按钮

- lib/server/model/project-code.js
- fix: 生成项目 process.env.BK_API_URL_TMPL 为空的问题
> fix: 生成项目 process.env.BK_API_URL_TMPL 为空的问题

- lib/server/controller/iam.js
> feat: code style

- lib/client/src/views/project/app-perm-model/index.vue
> feat: 应用权限模型 注意事项文案修改

- lib/client/src/element-materials/modifier/component/props/index.vue
> fix(remote-chart): 修复chart远程函数失效的问题

- lib/client/src/components/methods/forms/edit-func-form.vue
> 解决新增保存并使用报错

- lib/client/src/views/project/app-perm-model/index.vue
> feat: 未部署到权限中心操作，删除时，直接物理删除

- lib/client/src/store/index.js
- lib/server/controller/vue-code.js
- lib/server/model/page-code.js
- lib/server/model/project-code.js
- fix: 预览时不渲染绑定权限操作的组件，还是渲染原组件（通过 isRenderAppPermComponents 判断）
> fix: 预览时不渲染绑定权限操作的组件，还是渲染原组件（通过 isRenderAppPermComponents 判断）

- lib/client/src/views/project/app-perm-model/app-perm-model-sideslider.vue
> fix: 编辑时不检验 actionId

- lib/client/src/element-materials/modifier/component/perms/components/select-action.vue
- lib/server/model/iam-app-perm.js
- feat: 精简组件 targetData 里 renderPerms 的字段
> feat: 精简组件 targetData 里 renderPerms 的字段

- lib/client/src/views/project/app-perm-model/app-perm-model-sideslider.vue
- fix: 修复 是否关联资源 选择否时，关联资源并没有更新的问题
> fix: 修复 是否关联资源 选择否时，关联资源并没有更新的问题

- lib/client/src/element-materials/modifier/component/index.vue
- lib/client/src/element-materials/modifier/component/perms/components/select-action.vue
- lib/client/src/views/project/app-perm-model/app-perm-model-sideslider.vue
- lib/client/src/views/project/app-perm-model/index.vue
- lib/server/controller/iam.js
- lib/server/model/entities/iam-app-perm-action.js
- lib/server/model/migrations/sqls/20221004102006-update-sql-up.sql
- lib/server/model/sql/20221004/update.sql
1. 修复画布中的组件 权限 tab 错乱的问题
2. 权限操作同步到权限中心状态优化
> fix: 应用权限模型，画布组件绑定权限操作体验问题修复

- lib/client/src/views/project/app-perm-model/index.vue
> feat: 是否同步到权限中心 表头 tips

- lib/client/src/views/system/operation/stats/project/dim-project.vue
- lib/client/src/views/system/operation/stats/shared-mixin.js
- lib/client/src/views/system/operation/stats/user/dim-user.vue
- lib/server/controller/operation.js
> feat(运营数据): 用户和应用数据添加创建时间列

- lib/server/controller/operation.js
- 修复用户和应用数据按页面数排序未使用默认版本导致不准确的问题
> fix(运营数据): 修复用户和应用数据按页面数排序未使用默认版本导致不准确的问题

- lib/server/controller/release.js
- [xxxx](feat: remove test code)
> feat: remove test code

- lib/client/src/views/project/index.vue
- lib/server/controller/iam.js
- feat: 修复页面列表页导航颜色问题；增加注册系统管理员日志
> feat: 修复页面列表页导航颜色问题；增加注册系统管理员日志

- lib/server/controller/iam-migration-helper.js
- lib/server/model/iam-app-perm.js
> feat: 增加注册系统管理员日志

- lib/client/src/components/render/pc/widget/layout/index.vue
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/element-materials/modifier/template/complex-side/index.vue
- lib/client/src/element-materials/modifier/template/complex-top/index.vue
- lib/client/src/element-materials/modifier/template/editor/prop/color-options.js
- lib/client/src/element-materials/modifier/template/editor/prop/index.vue
- lib/client/src/element-materials/modifier/template/info.vue
- lib/client/src/element-materials/modifier/template/top-menu/base-menu-template.css
- lib/client/src/element-materials/modifier/template/top-menu/base-menu-template.tsx
> feat: 导航主题体验优化

- lib/client/src/components/patch/bkCharts/bk-chart-config.js
- lib/client/src/components/patch/bkCharts/bkCharts.vue
- lib/client/src/components/patch/bkCharts/index.js
- lib/client/src/components/variable/variable-select/index.vue
- lib/client/src/element-materials/materials/bk/bk-charts-bar/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-bubble/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-line/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-pie/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-radar/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-scatter/index.js
- lib/client/src/element-materials/materials/bk/charts-bar/index.js
- lib/client/src/element-materials/materials/bk/charts-line/index.js
- lib/client/src/element-materials/materials/bk/charts-pie/index.js
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/element-materials/modifier/component/props/index.vue
> wupdate(bkchart): 图表配置优化

- lib/client/src/components/patch/bkCharts/bk-chart-config.js
- lib/server/project-template/project-init-code/lib/client/src/components/bkCharts/bk-chart-config.js
- lib/server/project-template/project-init-code/lib/client/src/components/bkCharts/index.vue
> update(bkchart): bkcharts代码生成模板优化

- lib/server/model/page-code.js
> fix(bkchart): 修复bkchart远程配置预览无效的问题

- lib/client/src/components/patch/bkCharts/bkCharts.vue
- lib/client/src/element-materials/modifier/component/props/index.vue
- lib/server/model/page-code.js
> fix(bkchats): 修复bkcharts生成代码导致echarts依赖出错, 兼容remoteOptions

- lib/server/controller/project.js
> feat: add debug log

- lib/server/controller/iam.js
- lib/server/controller/project.js
- feat: 支持 权限中心申请权限时选择 无限制 的场景
> feat: 支持 权限中心申请权限时选择 无限制 的场景

- lib/server/controller/iam.js
- lib/server/decorator/authorization/index.js
> fix: 修复支持权限中心无限制权限申请引入的问题

- lib/client/src/views/help/index.vue
> feat: 修改层级关系

- lib/client/src/views/help/index.css
- lib/client/src/views/help/index.vue
- lib/client/src/views/home/index.vue
> feat: 修改选中状态

- lib/client/src/element-materials/materials/bk/bk-charts-bar/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-bubble/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-line/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-pie/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-radar/index.js
- lib/client/src/element-materials/materials/bk/bk-charts-scatter/index.js
- lib/server/controller/db-migration-helper.js
> fix(bkcharts): remote配置兼容，其配置同步至options，并支持远程函数

- .bk.production.env
> 补充 BK_ITSM_URL 变量

- lib/client/src/element-materials/materials/bk/bk-charts-line/index.js
- lib/client/src/element-materials/modifier/component/props/components/strategy/remote.vue
> fix(bk-charts): 优化bkcharts的options属性函数返回交互和校验

- lib/server/controller/iam.js
> feat: 修复页面列表左侧项目下拉框数据问题

- lib/server/controller/iam.js
- lib/server/controller/project.js
> feat: add project query log

- lib/client/src/views/project/data-source-manage/data-operation/children/json-query/children/common/select-bk-base-table.vue
> 优化bkbase结果表展示和搜索

- lib/client/src/components/render/pc/resolve-component.vue
- lib/client/src/element-materials/materials/bk/divider/index.js
- lib/client/src/element-materials/modifier/component/slots/render-slot.vue
> fix(divider): 分割线体验问题修复

- lib/client/src/css/bk-patch.css
> feat: 导航最小宽度优化

- lib/client/src/store/modules/data-source.js
- lib/client/src/views/project/data-source-manage/data-table/data-manage/index.vue
- lib/server/controller/data-source.js
- lib/server/service/common/online-db-service.js
> 开源版同内部版一致显示预发布和生产环境表结构及数据管理

- lib/client/src/components/filelib/helper.ts
- lib/client/src/components/filelib/upload.vue
- lib/client/src/components/src-input/file-modal.vue
- lib/client/src/views/project/file-manage/index.vue
> feat: 调整上传文件的大小和数量限制

- lib/client/src/components/filelib/list-table.vue
- lib/client/src/components/variable/variable-select/components/variable.vue
- lib/client/src/views/project/component-manage/all/components/render-list.vue
- lib/client/src/views/project/component-manage/useing/index.vue
- lib/client/src/views/project/credential-manage.vue
- lib/client/src/views/project/version-manage/index.vue
- lib/client/src/views/system/index.vue
- lib/client/src/views/system/operation/index.vue
- lib/client/src/views/system/operation/stats/comp/dim-comp.vue
- lib/client/src/views/system/operation/stats/comp/index.vue
- lib/client/src/views/system/operation/stats/func/dim-func.vue
- lib/client/src/views/system/operation/stats/func/index.vue
- lib/client/src/views/system/operation/stats/project/dim-project.vue
- lib/client/src/views/system/operation/stats/project/index.vue
- lib/client/src/views/system/operation/stats/user/dim-user.vue
- lib/client/src/views/system/operation/stats/user/index.vue
> fix: 表格样式和tab布局页面样式优化

- package.json
> fix: 预览时，时间选择器点击多次回车的问题

- lib/client/src/components/methods/forms/create-func-from-market-sideslider.vue
- lib/client/src/components/methods/forms/edit-func-form.vue
- lib/client/src/components/methods/forms/edit-func-sideslider.vue
- lib/client/src/components/methods/forms/edit-market-func-sideslider.vue
- lib/client/src/components/methods/forms/form-items/monaco.vue
- lib/client/src/components/variable/variable-form/index.vue
- lib/shared/custom-error.js
- lib/shared/function/helper.js
> 函数自动修复提示优化

- lib/client/src/views/project/app-perm-model/index.vue
> update: 应用权限模型提示文案颜色

- lib/client/src/router/index.js
- lib/client/src/views/help/docs/courses.md
- lib/client/src/views/help/index.vue
> 添加课程实战文档和视频

- lib/client/src/views/edit-nocode/index.vue
- lib/client/src/views/index/components/page-list/index.vue
- lib/client/src/views/project/index.vue
- lib/client/src/views/system/index.vue
> fix: 导航样式优化

- lib/client/src/components/app-header.vue
> feature: 导航最小宽度限制

- lib/client/src/views/project/component-manage/all/components/render-list.vue
> 自定义组件更新时间展示为浏览器时区时间

- lib/client/src/element-materials/materials/bk/divider/index.js
> fix(divier): 分割线禁止拉伸高度 & 修复分割线的bug

- lib/client/src/components/render/pc/tools/lesscode-tool/hooks/use-slot.js
- lib/client/src/element-materials/materials/bk/divider/index.js
> fix(divider): 修复divider的text属性不显示的问题

- lib/client/src/views/system/project-manage/children/list-card.vue
- lib/client/src/views/system/template-market.vue
- 设置应用描述tooltips的allowHTML为false解决导航展示异常问题
> fix: 设置应用描述tooltips的allowHTML为false解决导航展示异常问题

- bk.config.js
- lib/client/src/views/project/router-manage/children/bind-route-form.vue
- lib/client/src/views/project/router-manage/children/bind-route-selector.vue
- lib/client/src/views/project/router-manage/index.vue
- lib/client/src/views/project/router-manage/route-list.vue
- lib/server/controller/route.js
- lib/server/model/project-code.js
- lib/shared/route/helper.js
> feat: 应用根路由支持绑定跳转到移动端路由

- lib/client/src/element-materials/core/static/get-material.js
> fix(p): 修复P标签在移动端和PC端配置覆盖的问题

- lib/client/src/views/system/operation/stats/project/dim-project.vue
- lib/server/controller/operation.js
> feat(运营数据): 应用数据添加创建者列

- lib/client/src/views/project/router-manage/children/bind-route-selector.vue
- lib/client/src/views/project/router-manage/route-list.vue
- lib/server/controller/route.js
- 修复没有PC根路径时根路由无法绑定移动端路由的问题及根路由支持解除绑定
> fix: 修复没有PC根路径时根路由无法绑定移动端路由的问题及根路由支持解除绑定

- lib/client/src/views/index/components/operation-area/index.vue
> feat:增加交互组件检测和使用提示

- lib/client/src/components/render/pc/tools/lesscode-tool/index.vue
> feat:增加悬停提示可点击组件id选中特性

- lib/client/src/common/util.js
- lib/client/src/components/render/pc/tools/lesscode-margin/hooks/use-margin.js
- lib/client/src/components/render/pc/tools/lesscode-resize/hooks/use-resize.js
- lib/client/src/components/render/pc/widget/free-layout.vue
- lib/client/src/element-materials/materials/vant/field/index.js
- lib/shared/util.js
> feature: 拖拽操作时自适应单位 & 优化移动端拖拽体验

- lib/client/src/components/project/type-select.vue
- lib/client/src/router/index.js
- lib/client/src/views/project/index.vue
> feat:功能页面增加文档指引

- lib/client/src/views/project/component-manage/all/components/render-list.vue
> perf:"统一功能页面文档指引"

- lib/client/src/components/methods/forms/form-items/children/debug/param.vue
- lib/client/src/components/methods/forms/form-items/monaco.vue
- lib/client/src/components/monaco.vue
> 函数调试体验问题修复

- lib/client/src/components/methods/choose-function/index.vue
- lib/client/src/components/variable/variable-select/components/variable.vue
- lib/client/src/components/variable/variable-table.vue
- lib/client/src/views/project/variable-manage.vue
> 变量支持使用标识进行搜索

- lib/client/src/components/flow-form-comp/form/constants/forms.js
- lib/client/src/components/flow-form-comp/form/fieldItem.vue
- lib/client/src/components/flow-form-comp/form/fields/rate.vue
- lib/client/src/components/flow-form-comp/form/index.vue
- lib/client/src/components/flow-form-comp/form/util/index.js
- lib/client/src/components/project/create-page-dialog.vue
- lib/client/src/components/render-nocode/data-manage/index.vue
- lib/client/src/components/render-nocode/form/components/form-edit/association-value/components/rateValueRule.vue
- lib/client/src/components/render-nocode/form/components/form-edit/association-value/linkage.vue
- lib/client/src/components/render-nocode/form/components/form-edit/association-value/relation-rules.vue
- lib/client/src/components/render-nocode/form/components/form-edit/default-value.vue
- lib/client/src/components/render-nocode/form/components/form-edit/fieldEdit.vue
- lib/client/src/components/render-nocode/form/components/form-edit/fieldElement.vue
- lib/client/src/components/render-nocode/form/index.vue
- lib/client/src/components/render-nocode/index.vue
- lib/client/src/views/edit-nocode/components/more-actions/data-manage-operate.vue
- lib/client/src/views/edit-nocode/index.vue
- lib/client/src/views/index/components/action-tool/components/preview.vue
- lib/client/src/views/index/index.vue
- lib/client/src/views/project/index.vue
- lib/client/src/views/project/page-manage/index.vue
- lib/client/src/views/system/project-manage/index.vue
- lib/server/project-template/project-init-code/lib/client/src/components/flow-form-comp/form/constants/forms.js
- lib/server/project-template/project-init-code/lib/client/src/components/flow-form-comp/form/fieldItem.vue
- lib/server/project-template/project-init-code/lib/client/src/components/flow-form-comp/form/fields/rate.vue
- lib/server/project-template/project-init-code/lib/client/src/components/flow-form-comp/form/index.vue
- lib/shared/no-code/constant.js
- lib/shared/no-code/helper.js
> feat:新增表单评分组件

- lib/client/src/components/flow-form-comp/form/fields/rate.vue
- lib/client/src/components/render-nocode/form/components/form-edit/association-value/components/rateValueRule.vue
> 修复评分组件值规则校验不通过问题

- lib/client/src/views/project/router-manage/route-list.vue
> perf:路由配置和导航布局关联

- lib/client/src/views/project/router-manage/route-list.vue
- lib/server/controller/route.js
- lib/server/model/route.js
> fix:修复路由设置是否可预览导航布局

- lib/client/src/common/util.js
- lib/client/src/components/render/pc/widget/free-layout.vue
> fix: 画布FreeLayout优化, 修复拖入组件超出布局组件的问题

- lib/client/index.html
- lib/client/preview.html
- lib/server/project-template/project-init-code/lib/client/index.html
> fix: html文件添加<meta viewport> 支持移动端

- lib/client/src/preview/router.js
- lib/client/src/views/index/index.vue
> 修复预览缓存清除逻辑

- .bk.development.env
- lib/client/src/App.vue
- lib/client/src/element-materials/core/index.js
- lib/client/src/element-materials/core/static/edit-node.js
- lib/client/src/element-materials/core/static/parse-data.js
- lib/client/src/store/index.js
- lib/client/src/store/modules/ai.js
- lib/client/src/views/index/components/action-tool/components/ai.vue
- lib/client/src/views/index/components/action-tool/index.vue
- lib/server/controller/ai.js
- lib/server/service/common/ai.js
> 通过 ai 生成画布 demo

- lib/client/src/views/project/data-source-manage/data-table/common/import.vue
- lib/client/src/views/project/data-source-manage/data-table/data-manage/render-data.vue
- lib/server/controller/data-source.js
- lib/shared/data-source/constant.js
- lib/shared/data-source/data-parse/common.js
- lib/shared/data-source/data-parse/data-parser/json-parser.js
- lib/shared/data-source/data-parse/data-parser/sql-parser.js
- lib/shared/data-source/helper.js
- tsconfig.json
> 数据导入支持更新和去重导入

- lib/server/controller/data-source.js
> 数据导入体验问题修复

- lib/client/src/common/fully-import.js
- lib/client/src/common/vant.js
- lib/client/src/components/patch/widget-vant-date-time-picker/index.js
- lib/client/src/components/patch/widget-vant-date-time-picker/index.vue
- lib/client/src/components/render/mobile/common/simulator-mobile.vue
- lib/client/src/element-materials/materials/vant/date-time-picker/index.js
- lib/client/src/element-materials/materials/vant/index.js
- lib/server/model/project-code.js
- lib/server/project-template/project-init-code/lib/client/src/components/patch/vant-widget/index.js
- lib/server/project-template/project-init-code/lib/client/src/components/patch/vant-widget/widget-vant-date-time-picker.vue
- package.json
> feat: 移动端新增交互式组件 -- 日期选择器

- lib/server/service/common/online-db-service.js
- lib/shared/data-source/constant.js
- lib/shared/data-source/data-parse/common.js
- lib/shared/data-source/data-parse/struct-parser/sql-parser.js
> 修改 unique 字段逻辑

- lib/client/src/directives/en-class.js
- lib/client/src/directives/en-style.js
- lib/client/src/directives/index.js
- lib/client/src/main.js
> feature: 添加处理国际化样式指令

- lib/shared/page-code/script/vue2/methods.js
> fix: 国际化词条语法错误

- lib/shared/page-code/script/vue2/handle-var-and-func.js
- lib/shared/page-code/template/page/prop.js
- lib/shared/page-code/template/page/slot.js
> fix: shared目录引用国际化方法路径错误

- lib/shared/page-code/template/page/prop.js
> fix: 修复vant-ui v-model绑定的源码问题

- lib/client/src/preview/index.js
> fix: 画布预览国际化出错

- lib/client/src/views/project/layout/components/layout-dialog.vue
> fix: 修复新建模板弹窗的报错问题

- lib/client/src/views/index/index.vue
- lib/shared/variable/helper.js
> 离开页面的时候清除page数据

- lib/client/src/views/index/index.vue
> 退出页面的时候清除 LC 数据

- lib/client/src/views/index/index.vue
> 退出页面清空 路由 & platform 数据

- lib/client/src/views/help/docs/custom.md
- package.json
> vue3体验问题修复

- lib/client/src/components/api/common/single-scheme.tsx
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.tsx
> 修复函数和api number 数据类型

- lib/client/src/common/util.js
> fix: 修复组件在百分比宽度下拖拽报错的问题

- lib/client/src/components/render-nocode/components/layout/index.vue
> 修复vue2滚动条样式冲突

- lib/shared/page-code/script/vue2/handle-var-and-func.js
> 生成源码携带 preview 数据

- lib/client/src/components/render/pc/tools/lesscode-loading/index.js
- lib/client/src/element-materials/materials/vue2/bk/block/index.js
- lib/client/src/element-materials/materials/vue3/bk/block/index.js
> 修复block高度100%的问题

- lib/client/src/components/api/common/single-scheme.tsx
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.tsx
> 修复number输入变量的场景

- lib/client/src/views/project/page-manage/children/use-page-operation.js
> fix: 页面管理流程提单页顶部编辑入口跳转路径修复

- lib/client/src/components/methods/forms/form-items/detail.vue
> 数据源api体验优化

- lib/server/model/project-code.js
- lib/shared/function/helper.js
> 支持函数变量嵌套使用

- lib/client/src/components/render/pc/resolve-component/resolve-component.js
- lib/client/src/components/render/pc/tools/lesscode-loading/index.postcss
- lib/client/src/components/template/save-template-dialog.vue
- lib/client/src/element-materials/materials/vue3/bk/sideslider/index.js
- lib/client/src/views/index/components/header-operate/common/use-preview-img.js
- lib/client/src/views/preview/preview-template.vue
- lib/shared/api/helper.js
- lib/shared/function/helper.js
> 修复保存预览图失败和宽度100%问题

- lib/server/model/page.js
> 修复复制页面携带pagecode的问题

- lib/client/src/components/render/hooks/component-action-use.js
- lib/client/src/components/render/mobile/index/index.js
- lib/client/src/components/render/pc/index/index.js
- lib/client/src/components/render/pc/render-component.js
- lib/client/src/components/render/pc/tools/lesscode-resize/hooks/use-full-width.js
- lib/client/src/components/render/pc/widget/block/block.js
- lib/client/src/components/render/pc/widget/column/column.js
- lib/client/src/element-materials/materials/vue3/bk/swiper/index.js
修复vue3 修改width不更新 & 移动端点击空白区取消选中
> 修复vue3 修改width不更新 & 移动端点击空白区取消选中

- lib/client/src/element-materials/materials/vue2/bk/swiper/index.js
- lib/client/src/element-materials/materials/vue3/bk/swiper/index.js
- lib/client/src/views/help/docs/custom.md
> 修改 swiper 配置 & 添加自定义组件框架代码库地址

- lib/client/src/components/render/mobile/widget/layout/empty-layout/empty-layout.js
- lib/client/src/components/render/mobile/widget/layout/tab-bar/tab-bar.js
- lib/client/src/components/render/pc/tools/lesscode-tool/index.js
- lib/client/src/components/render/pc/widget/free-layout/free-layout.js
> fix: 修复移动端漂浮栏滚动位置错误问题 & 修复自由布局的粘贴位置问题

- lib/server/project-template/vue2/project-init-code/package.json
- lib/server/project-template/vue3/project-init-code/package.json
> 固定 babel-preset-bk 版本

- lib/server/project-template/vue2/project-init-code/package.json
- lib/server/project-template/vue3/project-init-code/package.json
> 修改 preset env 版本

- lib/server/project-template/vue3/project-init-code/lib/client/src/components/apply-permission/apply-dialog.vue
> 修复vue3无权限table

- lib/client/src/components/render/pc/tools/lesscode-resize/hooks/use-full-width.js
> 修复自由布局铺满预览没生效

- lib/client/src/preview/component.js
- lib/client/src/views/index/components/material-panel/components/panel-icon/components/render-offcial-icon.vue
- lib/client/src/views/index/components/material-panel/components/panel-icon/components/render-project-icon.vue
> 修复自定义组件预览 & 系统icon异常

- lib/client/src/components/render/pc/resolve-component/resolve-component.postcss
- lib/client/src/element-materials/materials/vue2/bk/input/index.js
- lib/client/src/element-materials/materials/vue3/bk/input/index.js
> 修复容器布局位置 & input 放开number类型

- lib/client/src/element-materials/modifier/component/styles/strategy/custom-style.vue
- lib/client/src/views/index/components/action-tool/components/quick-operation.vue
- lib/client/src/views/index/components/utils/sync-variable-value.js
> fix: 快捷键错误触发

- lib/client/src/components/render/pc/tools/lesscode-loading/index.js
- lib/client/src/components/render/pc/tools/lesscode-loading/index.postcss
> 修改组件 display-inline 表现

- lib/client/src/views/project/index.vue
> fix:项目下拉框,修改为暗色主题

- lib/client/src/views/index/components/material-panel/components/panel-component/components/select-base-component.vue
- lib/client/src/views/index/components/material-panel/components/panel-component/index.vue
> fix:切换组件类型触发范围仅在icon图标上

- lib/client/src/element-materials/modifier/page/components/page-setting.vue
> fix:修复页面配置版面中页面名字可修改

- lib/server/project-template/vue2/project-init-code/lib/client/src/components/html.vue
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/html.js
> 修复 v-html 预览跟部署后表现不一致

- lib/client/src/common/fully-import.js
- lib/client/src/components/render/pc/render-component.js
- lib/client/src/components/render/pc/widget/van-picker/index.js
- lib/client/src/element-materials/core/static/get-material.js
- lib/client/src/element-materials/materials/vue2/vant/date-time-picker/index.js
- lib/client/src/element-materials/materials/vue2/vant/picker/index.js
- lib/client/src/element-materials/materials/vue3/vant/date-time-picker/index.js
- lib/client/src/element-materials/materials/vue3/vant/index.js
- lib/client/src/element-materials/materials/vue3/vant/picker/index.js
- lib/client/src/preview/component.js
- lib/client/src/preview/index.js
- lib/client/src/views/index/components/material-panel/components/common/group-box/hacker.js
- lib/client/src/views/preview/preview-template.vue
- lib/server/controller/db-migration-helper.js
- lib/server/model/project-code.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/patch/vant-widget/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/patch/vant-widget/widget-van-picker.vue
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/patch/vant-widget/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/patch/widget-van-picker.vue
- lib/server/project-template/vue3/project-init-code/lib/client/src/main.js
> feat: Vue2 & Vue3 Picker/DatePicker组件集成

- lib/server/controller/variable.js
> 修复外部版缺失 preview 变量数据

- lib/client/src/element-materials/materials/vue2/element/avatar/index.js
- lib/client/src/element-materials/materials/vue2/element/bread-crumb/index.js
- lib/client/src/element-materials/materials/vue2/vant/date-time-picker/index.js
- lib/client/src/element-materials/materials/vue2/vant/h5-container/index.js
- lib/client/src/element-materials/materials/vue2/vant/picker/index.js
- lib/client/src/element-materials/materials/vue3/vant/check-box-group/index.js
- lib/client/src/element-materials/materials/vue3/vant/date-time-picker/index.js
- lib/client/src/element-materials/materials/vue3/vant/field/index.js
- lib/client/src/element-materials/materials/vue3/vant/h5-container/index.js
- lib/client/src/element-materials/materials/vue3/vant/number-keyboard/index.js
- lib/client/src/element-materials/materials/vue3/vant/pagination/index.js
- lib/client/src/element-materials/materials/vue3/vant/password-input/index.js
- lib/client/src/element-materials/materials/vue3/vant/picker/index.js
- lib/client/src/element-materials/materials/vue3/vant/radio-group/index.js
- lib/client/src/element-materials/materials/vue3/vant/rate/index.js
- lib/client/src/element-materials/materials/vue3/vant/search/index.js
- lib/client/src/element-materials/materials/vue3/vant/slider/index.js
- lib/client/src/element-materials/materials/vue3/vant/stepper/index.js
- lib/client/src/element-materials/materials/vue3/vant/switch/index.js
> feat:vue2 & vue3 组件属性和事件名与文档一致

- lib/client/src/components/api/common/validate.vue
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.tsx
- lib/server/controller/mock-data.js
- lib/server/project-template/vue2/project-init-code/lib/server/controller/mock-data.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/mock-data.js
函数校验体验问题 & mockdata 增加keywords参数
> 函数校验体验问题 & mockdata 增加keywords参数

- lib/client/src/components/render/mobile/widget/layout/tab-bar/tab-bar.js
> fix: 修复移动端布局编辑态跳转的问题

- lib/client/src/components/render/mobile/simulator-area/simulator-area.js
- lib/client/src/element-materials/modifier/page/components/children/page-route-setting.vue
> fix: 修复移动端修改页面路由、布局预览不刷新的问题

- bk.config.js
- lib/client/src/common/ai.js
- lib/client/src/store/modules/ai.js
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/content.vue
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/modal.vue
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/system-prompt.txt
- lib/server/controller/ai.js
- lib/server/decorator/send/index.js
- lib/server/service/business/ai.js
- lib/server/service/common/ai.js
- package.json
> 画布 ai prompt 优化

- lib/client/src/views/index/components/material-panel/components/panel-ai/components/content.vue
> ai设置不存在的属性的时候，让它重新思考

- lib/server/controller/mock-data.js
- lib/server/project-template/vue2/project-init-code/lib/server/controller/mock-data.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/mock-data.js
> getApiData 方法支持设置 axiosConfig

- lib/client/src/views/project/release/components/completed-info.vue
- lib/client/src/views/project/release/components/completed-log.vue
- lib/client/src/views/project/release/components/running-info.vue
- lib/client/src/views/project/release/components/running-log.vue
- lib/client/src/views/project/release/publish.vue
> fix:部署页面ui重构修复

- lib/client/src/components/methods/forms/form-items/detail.vue
- lib/client/src/components/variable/variable-form/index.vue
- lib/client/src/views/index/components/material-panel/components/panel-component/components/render-base-component.vue
- lib/client/src/views/index/components/material-panel/components/panel-component/components/render-custom-component.vue
- lib/client/src/views/index/components/material-panel/components/panel-component/index.vue
- lib/client/src/views/index/components/material-panel/components/panel-icon/components/render-offcial-icon.vue
- lib/client/src/views/index/components/material-panel/components/panel-icon/components/render-project-icon.vue
- lib/client/src/views/index/components/material-panel/components/panel-icon/index.vue
- lib/client/src/views/index/components/material-panel/components/panel-template/index.vue
- lib/client/src/views/index/index.vue
> feat: 画布物料区搜索位置固定,不滚动

- lib/client/src/element-materials/modifier/component/gird/index.vue
- lib/client/src/element-materials/modifier/component/index.vue
- lib/client/src/element-materials/modifier/component/props/index.vue
- lib/client/src/element-materials/modifier/component/slots/index.vue
- lib/client/src/element-materials/modifier/component/tab/index.vue
- lib/client/src/element-materials/modifier/component/utils/encodeRegexp.js
- lib/client/src/element-materials/modifier/component/utils/index.js
> feat:画布属性添加搜索功能

- lib/client/src/views/index/components/material-panel/components/panel-tree/index.vue
- lib/client/src/views/project/data-source-manage/data-operation/children/sql-query.vue
- lib/client/src/views/project/index.vue
- lib/client/src/views/project/layout/components/layout-dialog.vue
- lib/client/src/views/project/page-manage/index.vue
> fix: 体验样式修复

- lib/client/src/preview/index.js
> fix: 兼容侧边栏导航预览的page参数

- lib/shared/page-code/template/page/layout/help-menu-layout.js
> fix: 体验模版导航添加帮助菜单配置效果报错修复

- lib/client/src/preview/component.js
> fix: 修复移动端sidebar预览时，Vue3与Vue2样式冲突问题

- lib/client/src/common/vant.js
- lib/client/src/element-materials/materials/vue2/vant/grid/index.js
- lib/client/src/element-materials/materials/vue2/vant/index.js
- lib/client/src/element-materials/materials/vue3/vant/grid/index.js
- lib/client/src/element-materials/materials/vue3/vant/index.js
- lib/client/src/element-materials/modifier/component/slots/components/list/vant/index.js
- lib/client/src/element-materials/modifier/component/slots/render-config/vue2/vant/index.js
- lib/client/src/element-materials/modifier/component/slots/render-config/vue3/vant/index.js
> feat: 移动端添加宫格组件

- lib/client/src/common/ai.js
> 接口切换至 GPT4

- lib/client/src/element-materials/materials/vue2/bk/big-tree/index.js
- lib/client/src/element-materials/materials/vue2/bk/cascade/index.js
- lib/client/src/element-materials/materials/vue2/bk/process/index.js
- lib/client/src/element-materials/materials/vue2/bk/search-select/index.js
- lib/client/src/element-materials/materials/vue2/bk/tag-input/index.js
- lib/client/src/element-materials/materials/vue2/bk/transfer/index.js
- lib/client/src/element-materials/materials/vue2/element/cascade/index.js
- lib/client/src/element-materials/materials/vue2/element/transfer/index.js
- lib/client/src/element-materials/materials/vue3/bk/cascader/index.js
- lib/client/src/element-materials/materials/vue3/bk/process/index.js
- lib/client/src/element-materials/materials/vue3/bk/tag-input/index.js
- lib/client/src/element-materials/materials/vue3/bk/transfer/index.js
- lib/client/src/element-materials/materials/vue3/bk/tree/index.js
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/element-materials/modifier/component/props/components/strategy/value-key-item.vue
- lib/client/src/element-materials/modifier/component/props/components/strategy/value-key-option.vue
- lib/client/src/element-materials/modifier/component/props/index.vue
> feat: 组件配置对应获取反馈key

- lib/client/src/components/render/pc/render-component.js
- lib/client/src/components/render/pc/resolve-component/resolve-component.js
- lib/client/src/components/render/pc/widget/van-tab/index.js
- lib/client/src/components/render/pc/widget/van-tab/tab.postcss
- lib/client/src/element-materials/core/static/is-layout-type.js
- lib/client/src/element-materials/materials/vue2/vant/index.js
- lib/client/src/element-materials/materials/vue2/vant/widget-tab-panel/index.js
- lib/client/src/element-materials/materials/vue2/vant/widget-tab/index.js
- lib/client/src/element-materials/materials/vue3/vant/index.js
- lib/client/src/element-materials/materials/vue3/vant/widget-tab-panel/index.js
- lib/client/src/element-materials/materials/vue3/vant/widget-tab/index.js
- lib/client/src/element-materials/modifier/component/tab/index.vue
- lib/shared/page-code/template/page/component/index.js
> feat: 新增移动端tab（简化版）组件，提升tab组件使用体验

- lib/client/src/components/render-nocode/form/components/form-edit/components/serialEdit.vue
- lib/client/src/form-engine/fields/auto-counting/index.js
- lib/client/src/form-engine/fields/compute/index.js
- lib/client/src/form-engine/setter/common/default-value.vue
- lib/client/src/form-engine/setter/components/auto-counting-config/components/counting-rules-dialog.vue
- lib/client/src/form-engine/setter/components/auto-counting-config/index.vue
- lib/client/src/form-engine/setter/components/computed-config/components/compute-date.vue
- lib/client/src/form-engine/setter/components/computed-config/components/compute-number.vue
- lib/client/src/form-engine/setter/components/computed-config/components/formula-dialog.vue
- lib/client/src/form-engine/setter/components/computed-config/index.vue
- lib/client/src/form-engine/setter/components/table-config/index.vue
- lib/client/src/form-engine/setter/components/validate/index.vue
- lib/client/src/form-engine/setter/index.vue
- lib/client/src/form-engine/setter/setters.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/auto-counting/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/compute/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/auto-counting/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/compute/index.js
> 表单容器计算控件和自动编号控件更新

- lib/server/project-template/vue2/project-init-code/Procfile
- lib/server/project-template/vue2/project-init-code/app_desc.yaml
- lib/server/project-template/vue3/project-init-code/Procfile
- lib/server/project-template/vue3/project-init-code/app_desc.yaml
> 生成的应用切换为云原生应用

- lib/server/service/common/ai.js
> 提取ai模型到环境变量

- lib/server/project-template/vue2/project-init-code/Procfile
- lib/server/project-template/vue2/project-init-code/app_desc.yaml
- lib/server/project-template/vue3/project-init-code/Procfile
- lib/server/project-template/vue3/project-init-code/app_desc.yaml
> 回撤云原生应用相关修改

- lib/client/src/components/render/mobile/edit-area/edit-area.js
- lib/client/src/preview/children/app/app.js
- lib/shared/util.js
> fix: 修复vant的样式冲突问题

- lib/client/src/form-engine/fields/select/index.js
- lib/client/src/form-engine/fields/table/index.js
- lib/client/src/form-engine/setter/common/default-value.vue
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/buttons/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/filters/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/rich-text-viewer/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/cell-value/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/col-setting/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/field-view-value/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/row-actions/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/select/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/table/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/renderer/index.js
> 优化表单数据管理页vue3组件render

- lib/client/src/common/ai.js
- lib/client/src/element-materials/materials/vue2/bk/select/index.js
- lib/client/src/element-materials/modifier/component/directives/index.vue
- lib/client/src/element-materials/modifier/component/props/components/render-prop.vue
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/content.vue
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/system-prompt.txt
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-base.js
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-component.js
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-data-source.js
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-method.js
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-page.js
- lib/server/service/business/bk-base.js
> 支持ai生成 数据搜索、首页、数据分析 页面

- lib/client/src/form-engine/setter/components/data-source/components/worksheet-data.vue
- lib/server/controller/db-migration-helper.js
- lib/shared/form-field-protocol-transform/index.js
> upd: 表单页和表单数据管理页数据迁移到表单容器和表单数据管理容器

- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/edit/index.js
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/edit/index.postcss
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/components/buttons/index.postcss
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/buttons/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/buttons/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/index.postcss
- lib/shared/form-field-protocol-transform/index.js
> 刷新表单数据兼容部分字段不完整的情况

- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/edit/components/table/index.postcss
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/index.js
- lib/client/src/form-engine/fields/rich-text/index.js
- lib/client/src/views/index/components/header-operate/common/use-save-form-container.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/rich-text/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/rich-text/index.js
- lib/shared/form-field-protocol-transform/index.js
> 修复数据刷新的兼容问题

- lib/client/src/form-engine/fields/member/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/member/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/utils/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/member/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/utils/index.js
> vue3人员选择组件属性修改;源码删除无效引用

- lib/client/src/components/methods/forms/form-items/monaco.vue
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/send.vue
修改函数提示框的展示 & ai生成代码框enter的时候关闭推荐prompt
> 修改函数提示框的展示 & ai生成代码框enter的时候关闭推荐prompt

- lib/client/src/views/project/backend-module/children/backend/components/render-child-node.vue
- lib/client/src/views/project/backend-module/children/backend/components/render-header.vue
- lib/client/src/views/project/backend-module/children/backend/components/render-nodes.vue
- lib/client/src/views/project/backend-module/children/backend/components/render-parent-node.vue
- lib/client/src/views/project/backend-module/children/backend/index.vue
- lib/client/src/views/project/backend-module/children/backend/x6-render-vue/node.js
- lib/client/src/views/project/backend-module/children/backend/x6-render-vue/registry.js
- lib/client/src/views/project/backend-module/children/backend/x6-render-vue/view.js
- lib/client/src/views/project/backend-module/index.vue
- package.json
> saas 生成静态页面

- lib/server/service/business/data-table.js
- lib/server/service/business/project.js
> 应用导入导出支持第三方数据源

- lib/client/src/components/render/pc/widget/table/table.js
- lib/server/project-template/vue2/project-init-code/lib/server/controller/data-source.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/data-source.js
> 修复table更新数据逻辑

- lib/client/src/views/project/data-source-manage/data-table/table-design/table-list/third-part-db/components/render-main.vue
- lib/client/src/views/project/data-source-manage/data-table/table-design/table-list/third-part-db/components/render-sideslider.vue
- lib/server/controller/data-source.js
- lib/server/controller/third-part-db.js
> 第三方数据源体验问题修复

- lib/client/src/views/project/data-source-manage/data-table/table-design/table-list/third-part-db/components/render-main.vue
- lib/client/src/views/project/data-source-manage/data-table/table-design/table-list/third-part-db/components/render-sideslider.vue
- lib/server/controller/data-source.js
- lib/server/controller/third-part-db.js
- lib/server/service/business/preview-db-service.js
- lib/server/service/common/online-db-service.js
> 自动同步第三方db表结构

- lib/client/src/views/project/data-source-manage/data-operation/children/query-result.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
- lib/server/controller/data-source.js
- lib/server/project-template/vue2/project-init-code/lib/server/controller/data-source.js
- lib/server/project-template/vue2/project-init-code/lib/server/service/data-source.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/data-source.js
- lib/server/project-template/vue3/project-init-code/lib/server/service/data-source.js
- lib/server/service/business/data-source.js
> 数据源管理直接提交sql语句优化

- lib/client/src/preview/component.js
- lib/client/src/views/index/index.vue
- lib/server/controller/component.js
- lib/server/project-template/vue2/project-init-code/package.json
- package.json
> 打通业务组件和自定义组件

- lib/client/src/common/fully-import.js
- lib/shared/page-code/script/vue2/lifeCycle.js
> fix: 修复 swiper 组件注册与自定义组件冲突问题

- lib/client/src/element-materials/materials/vue2/vant/lucky-canvas/index.js
- lib/client/src/element-materials/materials/vue3/vant/lucky-canvas/index.js
- lib/client/src/views/preview/preview-template.vue
- lib/server/model/project-code.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/bk-lucky-canvas/index.vue
- lib/server/project-template/vue2/project-init-code/lib/client/src/main.js
- lib/server/project-template/vue2/project-init-code/package.json
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/bk-lucky-canvas/index.vue
- lib/server/project-template/vue3/project-init-code/lib/client/src/main.js
- lib/server/project-template/vue3/project-init-code/package.json
> update: 修复项目下载移动端组件缺失问题 & 模板预览问题

- lib/server/service/business/notice-center.js
- lib/shared/page-code/script/vue2/lifeCycle.js
> fix: 添加消息通知接口的容错 & swiper 初始化代码优化

- lib/server/model/project-code.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/main.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/main.js
> update: 修复部署报错的问题

- lib/client/src/components/render/pc/render-component.js
> fix: 交互式组件实现方案更新 & 适配 bk-lesscode-render 升级

- lib/client/src/components/api/common/scheme.css
- lib/client/src/components/api/common/single-scheme.tsx
- lib/client/src/components/api/common/validate.vue
- lib/client/src/components/methods/forms/form-items/children/body-params.vue
- lib/client/src/components/methods/forms/form-items/children/render-param-slot.tsx
- lib/client/src/components/render/pc/widget/table/table-column.js
- lib/client/src/element-materials/materials/vue3/bk/table/index.js
- lib/client/src/element-materials/modifier/component/slots/components/table.vue
- lib/client/src/element-materials/modifier/component/slots/render-config/vue3/bk/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/patch/widget-table-column.vue
- lib/shared/api/helper.js
- lib/shared/variable/helper.js
- package.json
> object跟array类型参数可绑定变量

- lib/client/src/components/render/pc/widget/table/table-column.js
- lib/client/src/element-materials/modifier/component/slots/components/table.vue
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/patch/widget-table-column.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/patch/widget-table-column.js
> table 支持状态列

- lib/client/src/element-materials/modifier/component/slots/components/table.vue
- lib/server/project-template/vue3/project-init-code/package.json
- package.json
> 修复table组件渲染问题

- lib/server/service/business/preview-db-service.js
> 忽略id不是primary key的第三方表

- lib/client/src/element-materials/modifier/component/slots/render-config/vue3/bk/index.js
> 修复 vue3 table自定义列偶现删除不了

- lib/server/service/common/online-db-service.js
> 数据源兼容 enum 类型

- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/edit/components/table/index.postcss
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/components/buttons/index.postcss
- lib/client/src/element-materials/modifier/component/form-container/components/data-source.vue
- lib/client/src/form-engine/fields/checkbox/index.postcss
- lib/client/src/form-engine/fields/radio/index.js
- lib/client/src/form-engine/fields/radio/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/buttons/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/checkbox/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/radio/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/radio/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/utils/condition-parser.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/buttons/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/checkbox/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/radio/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/radio/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/utils/condition-parser.js
- lib/server/service/business/nocode-form.js
> fix: 修复vue3应用表单样式及radio事件不生效问题

- lib/server/project-template/vue2/project-init-code/package.json
> vue2 项目安装公共依赖

- lib/client/src/element-materials/materials/vue3/bk/dialog/index.js
- lib/client/src/element-materials/materials/vue3/bk/sideslider/index.js
- lib/client/src/views/index/components/material-panel/components/select-panel/index.vue
- lib/server/controller/db-migration-helper.js
update: 刷数据库旧数据
- xxxx
- Fixes #
> fix: 修复 Vue3 交互式组件层级错误 & 无法隐藏的问题

- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/edit/components/table/index.js
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/components/table/index.js
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/components/table/row-actions/index.js
- lib/client/src/element-materials/modifier/form-editor-container/components/data-manage-container-element/events/index.vue
- lib/client/src/form-engine/layout/index.js
- lib/client/src/form-engine/setter/components/key/index.vue
- lib/client/src/form-engine/setter/index.vue
- lib/client/src/views/index/components/header-operate/common/use-save-form-container.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/row-actions/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/row-actions/index.js
> 数据管理容器操作列增加跳转操作

- lib/client/src/store/modules/data-source.js
- lib/server/controller/data-source.js
> modifyOnlineDb接口sql加密

- lib/client/src/components/methods/forms/form-items/monaco.vue
- lib/client/src/element-materials/modifier/component/events/children/describe-function/index.vue
- lib/client/src/store/modules/data-source.js
- lib/client/src/views/project/data-source-manage/data-operation/children/query-result.vue
- lib/client/src/views/project/data-source-manage/data-operation/index.vue
- lib/client/src/views/project/data-source-manage/data-table/table-design/table-list/third-part-db/components/render-aside.vue
- lib/client/src/views/project/data-source-manage/data-table/table-design/table-list/third-part-db/components/render-main.vue
- lib/server/project-template/vue2/project-init-code/lib/server/service/data-source.js
- lib/server/project-template/vue2/project-init-code/package.json
- lib/server/project-template/vue3/project-init-code/lib/server/service/data-source.js
- lib/server/project-template/vue3/project-init-code/package.json
- lib/server/service/business/data-source.js
- lib/shared/util.js
- package.json
> 修改base64加解密

- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/index.js
> fix: vue3表格分页参数修改

- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/components/table/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/data-manage-container/form-data-manage/components/table/index.js
> vue3应用操作列去掉index配置

- lib/client/src/components/render/pc/widget/table/table-column.js
- lib/client/src/components/render/pc/widget/table/table.js
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/content.vue
- lib/client/src/views/index/components/material-panel/components/panel-ai/components/system-prompt.txt
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-page.js
- lib/server/project-template/vue3/project-init-code/package.json
- package.json
> 修改ai使用模板逻辑，让其选择使用现有页面模板

- lib/client/src/components/help-doc-detail/docs/form-data-container.md
> docs: 更新文档

- lib/client/src/form-engine/renderer/index.js
- lib/client/src/form-engine/setter/components/val-linkage-rules/components/linkage.vue
- lib/client/src/form-engine/setter/components/val-linkage-rules/components/rate-value-rule.vue
- lib/client/src/form-engine/setter/components/val-linkage-rules/components/relation-rules.vue
- lib/client/src/form-engine/utils/condition-parser.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/utils/condition-parser.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/utils/condition-parser.js
> feat: 字段联动规则支持配置多种逻辑运算 --story=117349734

- lib/client/src/element-materials/materials/vue2/vant/icon/index.js
- lib/client/src/element-materials/materials/vue2/vant/image/index.js
- lib/client/src/element-materials/materials/vue2/vant/paragraph/index.js
- lib/client/src/element-materials/materials/vue3/vant/icon/index.js
- lib/client/src/element-materials/materials/vue3/vant/image/index.js
> fix: 修复组件缺失 H5 动画属性的问题

- lib/client/src/views/index/components/material-panel/components/panel-ai/components/system-prompt.txt
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-page.js
- lib/server/service/business/ai.js
> 优化 ai 使用模板交互

- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/utils/data-source.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/utils/data-source.js
> fix: 表单事件源码配置和预览不一致修复

- lib/client/src/element-materials/modifier/component/events/children/describe-function/render-ai.vue
- lib/server/model/project-code.js
> 事件AI在生成失败的时候，不清空用户输入的内容

- lib/client/src/components/render-nocode/form/components/form-edit/dataSourceDialog.vue
- lib/client/src/element-materials/core/helper/find-related-variable.js
- lib/client/src/form-engine/fields/member/index.js
- lib/client/src/form-engine/layout/index.js
- lib/client/src/form-engine/renderer/index.js
- lib/client/src/form-engine/setter/components/value/index.vue
- lib/client/src/form-engine/utils/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/utils/index.js
- lib/server/project-template/vue2/project-init-code/lib/shared/util.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/renderer/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/utils/index.js
- lib/server/project-template/vue3/project-init-code/lib/shared/util.js
- lib/shared/page-code/template/page/prop.js
- lib/shared/util.js
> 表单容器字段默认值支持变量 & 组件升级走查处理

- lib/client/src/views/project/data-source-manage/data-table/data-manage/render-data.vue
- lib/server/controller/data-source.js
- lib/server/service/business/data-source.js
> 导出sql的时候，数据使用数据库的时区

- lib/server/service/business/preview-db-service.js
> 预览时候区分第三方数据源和自建数据源

- lib/client/src/components/api/common/single-scheme.tsx
> 数据源api page参数默认为1

- lib/client/src/components/render-nocode/form/components/left-panel/index.vue
- lib/client/src/form-engine/layout/index.js
- lib/client/src/form-engine/layout/index.postcss
- lib/client/src/form-engine/material/group-item.vue
- lib/client/src/locales/lang/en.json
- lib/client/src/store/modules/flow/tpl.js
- lib/client/src/views/project/flow-manage-old/list/flow-list.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/bound-detail.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/create-binding.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/select-form-dialog.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/components/breadcrumb-nav.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/components/save-btn.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/fields-canvas.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/materials.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/modifiers.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/constants.js
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/node.vue
- lib/client/src/views/project/flow-manage/tpl-edit/index.vue
- lib/client/src/views/project/index.vue
- lib/client/src/views/project/project-data.js
- lib/server/controller/flow.js
> feat: 增加应用内是否有旧流程判断，动态设侧边导航项

- lib/client/src/store/modules/flow/task.js
- lib/client/src/views/index/components/header-operate/common/use-save.js
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/config/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/index.vue
- lib/client/src/views/project/flow-manage/tpl-list/create-flow-dialog.vue
- lib/client/src/views/project/index.vue
- lib/server/controller/flow.js
- lib/server/model/entities/flow-tpl.js
- lib/server/model/migrations/20240902162632-update-sql.js
- lib/server/model/migrations/sqls/20240902162632-update-sql-up.sql
- lib/shared/page-code/common/modelMethods.js
> feat: 任务状态对接BkFlow

- lib/client/src/element-materials/modifier/component/events/children/choose-flow-action.vue
- lib/client/src/views/project/index.vue
- lib/shared/page-code/common/modelMethods.js
> fix: vue2应用旧流程导航入口切换判断条件修改

- lib/client/src/components/render/pc/widget/flow-manage-container/edit/flow-manage-container.postcss
- lib/client/src/components/render/pc/widget/flow-manage-container/edit/index.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/const.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/process-overview.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/process-overview.postcss
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/index.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/index.postcss
> 添加 vue3 & 修复交互问题

- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/process-overview.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/index.js
- lib/server/model/project-code.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/const.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/main.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/const.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/main.js
> flowManage 组件适配下载和部署

- lib/client/src/views/index/components/material-panel/components/panel-ai/components/system-prompt.txt
- lib/client/src/views/index/components/material-panel/components/panel-ai/hooks/use-page.js
> 优化AI使用模板的流程

- lib/client/src/views/index/components/material-panel/components/select-panel/index.vue
> refactor: 移动端页面去掉表单编辑器相关菜单模块

- lib/client/src/element-materials/modifier/component/events/children/choose-flow-action.vue
- lib/server/controller/flow.js
> refactor: 画布元素事件绑定执行流程操作增加部署状态逻辑相关优化

- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/process-overview.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/index.js
> Feat integration bkflow

- lib/client/src/views/project/flow-manage/tpl-edit/canvas/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/data-processing-node/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/data-processing-node/processing-rule-edit.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/index.vue
- lib/server/controller/flow.js
- lib/server/utils/flow/index.js
> feat: 数据处理节点支持选择流程前置节点中的表单变量

- lib/client/src/views/project/flow-manage/tpl-edit/canvas/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/data-processing-node/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/constants.js
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/dnd.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/graph.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/node.vue
- lib/server/controller/flow.js
- lib/server/utils/flow/index.js
> refator: 增加系统自动添加数据处理节点逻辑

- lib/client/src/components/flow/nodeConfig/nodes/normal-node/node-form-setting/index.vue
- lib/server/utils/flow/index.js
> refator: 旧流程自动创建表单时表名统一做小写处理

- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/task-detail-sideslider/index.js
- lib/client/src/store/modules/flow/task.js
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/graph.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/node.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/render-graph/registry.js
- lib/client/src/views/project/flow-manage/tpl-edit/debug/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/debug/node-operate-sideslider.vue
- lib/client/src/views/project/flow-manage/tpl-edit/index.vue
- lib/server/controller/flow.js
- lib/server/utils/flow/index.js
> feat: 流程编辑页测试执行功能

- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/task-detail-sideslider/index.postcss
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/task-detail-sideslider/manual-node-form.postcss
- lib/client/src/store/modules/flow/task.js
- lib/client/src/views/project/flow-manage/tpl-edit/debug/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/debug/manual-node.js
- lib/client/src/views/project/flow-manage/tpl-edit/debug/node-operate-sideslider.vue
> feat: 测试执行流程节点处理面板

- lib/client/src/views/project/flow-manage/tpl-edit/debug/index.vue
> fix: 退出测试执行流程

- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/task-detail-sideslider/index.js
- lib/client/src/form-engine/fields/date/index.js
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/components/save-btn.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/node-fields-canvas/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/debug/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/debug/node-operate-sideslider.vue
- lib/client/src/views/project/flow-manage/tpl-edit/index.vue
- lib/server/controller/flow.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/date/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/datetime/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/date/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/datetime/index.js
- lib/shared/page-code/common/modelMethods.js
> fix: 流程测试相关问题修复

- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/task-detail-sideslider/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/task-detail-sideslider/manual-node-form.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/task-detail-sideslider/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/task-detail-sideslider/manual-node-form.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/flow.js
> refactor: 应用生成源码修改

- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/task-detail-sideslider/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/task-detail-sideslider/manual-node-form.js
> fix: vue3应用流程数据管理容器render函数语法配置修复

- lib/server/model/project-code.js
> refactor: 应用生成网关增加新版流程判断

- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.postcss
- lib/server/project-template/vue2/project-init-code/lib/server/service/form.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.postcss
- lib/server/project-template/vue3/project-init-code/lib/server/service/form.js
> refactor: 部署应用时网关为自己授权

- lib/client/src/element-materials/modifier/component/data-manage-container/index.vue
> fix: 体验问题修复（文案优化）

- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue2/project-init-code/lib/server/util/flow/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.postcss
- lib/server/project-template/vue3/project-init-code/lib/server/util/flow/index.js
- lib/server/utils/flow/index.js
> fix: 修复部署应用的流程数据管理容器问题

- lib/client/src/element-materials/modifier/component/data-manage-container/index.vue
- lib/server/app.browser.js
- lib/server/controller/flow.js
- lib/server/controller/release.js
- lib/server/custom-global.js
- lib/server/middleware/auth.js
- lib/server/model/project-code.js
- lib/server/project-template/vue2/project-init-code/lib/server/controller/flow.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/flow.js
- lib/server/service/business/flow.js
- lib/server/service/business/open-api.js
- lib/server/utils/flow/index.js
> refactor: 平台和应用在bkflow动态注册空间

- lib/client/src/views/project/flow-manage/tpl-edit/debug/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/debug/node-operate-sideslider.vue
> refactor: 去掉vue composition-api模块的导入

- lib/client/src/element-materials/materials/vue2/vant/h5-container/index.js
- lib/client/src/views/preview/preview-template.vue
> fix: 修复移动端模板预览的问题

- lib/server/model/project-code.js
> refactor(project-code):  增加对数据库中未设置框架的兼容性处理 & 默认为 vue2

- lib/client/src/views/preview/preview-template.vue
> refactor(preview): 增加移动端预览的高度调整逻辑【仅在移动端预览时，设置 swiper-container 的高度】

- lib/client/src/element-materials/modifier/component/h5-page/index.vue
- lib/shared/page-code/template/page/layout/mobile-layout.js
- 优化新增页面的插入逻辑
- 调整页面组件的样式以适应新增和删除功能
- 为每个swiper slide添加Vue指令支持以实现动态绑定
- xxxx
- Fixes #
>  feat(移动布局): 增强移动页面容器功能 & 优化交互 & 支持签到模板的交互

- lib/server/service/business/data-source.js
> 修改导出的date格式

- lib/client/src/element-materials/materials/vue2/bk/sideslider/index.js
> fix(sideslider): 修复 transfer 属性静态值问题

- package.json
> 升级 @blueking/ai-blueking

- lib/server/service/common/online-db-service.js
> 修改sql参数的写法

- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/page-bound-editor.vue
> refactor: 关联表单页编辑

- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/page-bound-editor.vue
> fix: 流程关联页面问题修复

- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/page-bound-editor.vue
- lib/server/controller/flow.js
> fix: 流程绑定页面id取值不正确问题修复

- lib/client/src/components/render/pc/render-component.js
- lib/client/src/components/render/pc/tools/lesscode-tool/hooks/use-check-form-engine.js
- lib/client/src/components/render/pc/widget/flow-manage-container/edit/index.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/process-overview.js
- lib/client/src/components/render/pc/widget/flow-workbench-container/edit/index.js
- lib/client/src/components/render/pc/widget/flow-workbench-container/edit/index.postcss
- lib/client/src/components/render/pc/widget/flow-workbench-container/preview/index.js
- lib/client/src/element-materials/materials/vue2/bk/flow-workbench-container/index.js
- lib/client/src/element-materials/materials/vue2/bk/index.js
- lib/client/src/element-materials/materials/vue3/bk/flow-workbench-container/index.js
- lib/client/src/element-materials/materials/vue3/bk/index.js
- lib/client/src/preview/component.js
- lib/client/src/views/index/components/material-panel/components/panel-form-engine/index.vue
- lib/server/controller/flow.js
- lib/server/model/entities/flow-task.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-workbench-container/index.js
- lib/server/project-template/vue2/project-init-code/lib/server/controller/flow.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-workbench-container/index.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/flow.js
- lib/server/service/business/flow.js
- lib/server/service/common/data-service.js
> feat: 增加流程工作台容器

- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/components/table/index.js
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/index.js
- lib/client/src/components/render/pc/widget/data-manage-container/form-data-manage/preview/index.postcss
- lib/client/src/components/render/pc/widget/flow-manage-container/edit/flow-manage-container.postcss
- lib/client/src/components/render/pc/widget/flow-manage-container/edit/index.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/process-overview.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/components/process-overview.postcss
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/index.js
- lib/client/src/components/render/pc/widget/flow-manage-container/preview/index.postcss
- lib/client/src/components/render/pc/widget/flow-workbench-container/edit/index.js
- lib/client/src/components/render/pc/widget/flow-workbench-container/edit/index.postcss
- lib/client/src/components/render/pc/widget/flow-workbench-container/preview/index.js
- lib/client/src/components/render/pc/widget/flow-workbench-container/preview/index.postcss
- lib/client/src/store/modules/flow/tpl.js
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/page-bound-editor.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/index.vue
- lib/client/src/views/project/flow-manage/tpl-list/index.vue
- lib/server/controller/flow.js
> feat: 流程列表页增加生成工作台页面入口以及流程工作台体验问题修复

- lib/client/src/components/render/pc/widget/flow-manage-container/edit/flow-manage-container.postcss
- lib/client/src/components/render/pc/widget/flow-manage-container/edit/index.js
- lib/client/src/components/render/pc/widget/flow-workbench-container/edit/index.js
- lib/client/src/components/render/pc/widget/flow-workbench-container/edit/index.postcss
- lib/client/src/store/modules/flow/tpl.js
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/form-binding-config/page-bound-editor.vue
- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/index.vue
- lib/client/src/views/project/flow-manage/tpl-edit/config/index.vue
- lib/client/src/views/project/flow-manage/tpl-list/index.vue
- lib/server/controller/flow.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-manage-container/index.postcss
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-workbench-container/index.js
- lib/server/project-template/vue2/project-init-code/lib/client/src/components/flow-workbench-container/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/index.postcss
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-workbench-container/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-workbench-container/index.postcss
> refactor: 流程管理页关联工作台页面支持绑定已有页面

- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/components/process-overview.js
> vue3应用源码属性取值修复

- lib/server/project-template/vue3/project-init-code/lib/client/src/components/flow-manage-container/index.js
> vue3应用源码ref设置不正确修复

- lib/server/project-template/vue2/project-init-code/lib/client/src/components/form-engine/fields/member/index.js
- lib/server/project-template/vue3/project-init-code/lib/client/src/components/form-engine/fields/member/index.js
> vue3应用源码人员选择器host值注入时机修改

- lib/client/src/views/project/flow-manage/tpl-edit/canvas/node-detail/manual-node/index.vue
> fix: 人工节点复用表单模式绑定表单页失败修复

- lib/server/controller/flow.js
- lib/server/controller/release.js
- lib/server/custom-global.js
- lib/server/project-template/vue2/project-init-code/lib/server/controller/flow.js
- lib/server/project-template/vue2/project-init-code/lib/server/custom-global.js
- lib/server/project-template/vue3/project-init-code/lib/server/controller/flow.js
- lib/server/project-template/vue3/project-init-code/lib/server/custom-global.js
- lib/server/service/business/flow.js
> refactor: 上云版、社区版bkflow网关名称区分
